Adição da Entidade Talhão
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #100
Opened 2022-03-05 16:34 UTC by thiagohdaqw

## Descrição

A entidade PLANTIO foi normalizada, assim, criando a entidade Talhão.

## Está consertando alguma issue aberta?

- #91 
- 
## Tarefas gerais realizadas
- Modelagem da entidade Talhao
- Diagrama de classes atualizado
- DER atualizado
- MER atualizado
- DLD atualizado
- Dicionario de Dados atualizado

2022-03-06 23:46 UTC, Denniel-sudo approved these changes

2022-03-06 23:46 UTC, Denniel-sudo commented on docs/modelagem/estatica/diagrama_de_classes.md
> +- Todos os atributos públicos possuem métodos Getters e Setters, não foram incluídos no diagama para facilitar a visualização.
Na linha 29 está escrito "diagama" ao invés de "diagrama"

2022-03-06 23:47 UTC, Denniel-sudo requested changes
Muito bom trabalho, só foi encontrado essa palavra

2022-03-07 14:12 UTC, Joao-Moura requested changes
Parabéns pelo trabalho. A única alteração que eu tenho pra citar é adicionar os documentos alterados em um novo tópico nessa entrega, assim como feito na passada.
Exemplo:
```yml
- Iniciativas Extras:
    - Documentos alterados:
        - MER
        - DER
        - ...
```
No mais é isso, novamente parabéns pelo trabalho.

2022-03-07 15:42 UTC, Joao-Moura approved these changes
Boa rapaziada

2022-03-08 00:06 UTC, Denniel-sudo approved these changes
Boa pessoal!

2022-03-08 00:07 UTC, merged