Criação documento GRASP(s)
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #101
Opened 2022-03-06 16:16 UTC by CarlosFiuza

## Descrição
Criação de artefato para documentação dos estudos acerca dos padrões GRASP(s)

## Está consertando alguma issue aberta?
#93 

## Tarefas gerais realizadas
- Estudo sobre GRASP(s)
- Documentação

2022-03-06 16:50 UTC, VitorLamego approved these changes
Meus parabéns, o documento ficou muito bom e os padrões de projetos muito bem explicados. Senti falta das imagens nos últimos padrões, mas não chega a ser um fator impeditivo para aprovação do PR.

Deixei apenas algumas pontuações sobre melhorias na redação, mas estarei aprovando por ser algo muito pequeno e não necessitar de outra revisão. Parabéns!

2022-03-06 16:50 UTC, VitorLamego commented on docs/padroes_projetos/estudos/grasp.md
> +<p align="justify" style="text-indent: 20px">Como forma de ter um melhor preparo para a aplicação dos padrões GRASP no projeto assim como um melhor entendimento do conteúdo, este documento foi elabor
Faltou uma ',' após "projeto" -> "no projeto, assim como um melhor entendimento do conteúdo, ..."

2022-03-06 16:50 UTC, VitorLamego commented on docs/padroes_projetos/estudos/grasp.md
> +<p align="justify" style="text-indent: 20px"> Existem muitas formas de se aplicar a indireção. O padrão Controller é um exemplo de indireção, outro excelente exemplo de aplicação deste conceito é a I
Ao invés de utilizar "padrão Controller" poderia utilizar "padrão Controlador", uma vez que foi utilizado dessa forma anteriormente no documento.

2022-03-06 21:48 UTC, brenno-silva requested changes
Bom trabalho pessoal, só um pequeno erro de formatação.

2022-03-06 21:48 UTC, brenno-silva commented on docs/padroes_projetos/estudos/grasp.md
> +<p>"Isso permite que objetos da mesma hierarquia de tipo se comportem de forma diferente em tempo de execução simplesmente associando a chamada de método de interface à instância de tempo de execução
A formatação está diferente dos outros parágrafos

2022-03-07 11:55 UTC, brenno-silva approved these changes
Muito bom!

2022-03-07 12:46 UTC, merged