#67 Protótipo Alta Fidelidade
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #103
Opened 2022-03-06 17:28 UTC by VitorLamego

## Descrição
Foi elaborado o documento de protótipo de alta fidelidade para o projeto em questão. Além dessa elaboração, foi adicionado à wiki um documento contendo a metodologia utilizada e comentários referente a essa parte do projeto.

## Está consertando alguma issue aberta?
#67 

## Tarefas gerais realizadas
- Desenvolvimento do Protótipo de Alta Fidelidade
- Adição do documento na wiki

2022-03-06 22:37 UTC, Joao-Moura requested changes
Curti bastante o design, como sou do back não tenho muitas opinões sobre o design. No mais é isso, deixei umas alterações pequenas e parabéns pessoal.

2022-03-06 22:37 UTC, Joao-Moura commented on docs/base/prototipacao/alta_fidelidade.md
> +1.0   | 06/03/2022 | Criação do documento, adição da introdução, metodologia e protótipo | Vitor Lamego
Dividir o versionamento em vários, 1 pra criação do doc (pode ser só você Lamego), 1 para introdução e metodologoia (pode ser só você também) e 1 para a criação do protótipo (nesse caso bota todo mundo que participou da criação)

2022-03-06 22:37 UTC, Joao-Moura commented on docs/base/prototipacao/alta_fidelidade.md
> +<p style="text-align: justify; text-indent: 20px"> Vale ressaltar que o protótipo está sujeito a mudanças durante o projeto, uma vez que podem surgir novas necessidades não identificadas no momentos,
```suggestion
<p style="text-align: justify; text-indent: 20px"> Vale ressaltar que o protótipo está sujeito a mudanças durante o projeto, uma vez que podem surgir novas necessidades não identificadas no momento, ou até mesmo ideias e sugestões de melhorias visuais.
```

2022-03-06 22:37 UTC, Joao-Moura commented on docs/base/prototipacao/alta_fidelidade.md
> +<p style="text-align: justify; text-indent: 20px"> Abaixo segue o protótipo de alta fidelidade, sendo este o projeto que mais se identifica com o design final do projeto.
```suggestion
<p style="text-align: justify; text-indent: 20px"> Abaixo segue o protótipo de alta fidelidade, sendo este a confecção que mais se identifica com o design final do projeto.
```

2022-03-06 23:28 UTC, Denniel-sudo approved these changes
Ficou muito bom galera, gostei do padrão de cores e construção das telas

2022-03-06 23:30 UTC, thiagohdaqw approved these changes

2022-03-07 00:22 UTC, Joao-Moura approved these changes
Do balacubaco 🦔

2022-03-07 02:18 UTC, RcleydsonR approved these changes
Excelente trabalho galera, acho que esse protótipo traz o que a gente precisa, sendo simples e intuitivo com botões e informações bem aparentes, achei interessante deixar no texto a possível necessidade de mudança, mas no mais é isso mesmo ! 🥂

2022-03-07 02:46 UTC, PauloAbiAcl approved these changes

2022-03-07 15:16 UTC, vital14 reviewed
bom trabalho pessoal!

2022-03-07 15:29 UTC, merged