Documentação review sprint 4 e planning sprint 5
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #121
Opened 2022-03-16 01:57 UTC by PauloAbiAcl

## Descrição
Documentação do ritual de review da sprint 4 e do ritual de planning da sprint 5

## Está consertando alguma issue aberta?
#120 

## Tarefas gerais realizadas
- Documentação review
- Documentação planning

2022-03-16 02:02 UTC, Joao-Moura requested changes
Show de bola, apenas algumas corresções

2022-03-16 02:02 UTC, Joao-Moura commented on docs/sprints/review_4.md
> +|--|:-:|--|
Em vez de colocar "Em andamento" coloca "Dívida Técnica"

2022-03-16 02:02 UTC, Joao-Moura commented on docs/sprints/review_4.md
> +- Ficou faltando as informações referentes a issue "Splash Screen", que não foi aberta.
```suggestion
- Nessa Sprint houve bastante dificuldade em relação a entrega das issues do front-end, seja por falta de tempo, ou falta de organização, além do que a equipe está um pouco enferrujada em relação a linguagem. Em relação ao Back-end, tudo foi entrego em excelente prazo e resolvido conforme o planejado. Por fim, ficaram faltando as informações referentes a issue "Splash Screen", que não foi aberta.
```

2022-03-16 02:16 UTC, Joao-Moura approved these changes

2022-03-16 18:51 UTC, RcleydsonR requested changes
Alguns erros ortográficos, mas no geral tá ótimo!

2022-03-16 18:51 UTC, RcleydsonR commented on docs/sprints/review_4.md
> +- Nessa Sprint houve bastante dificuldade em relação a entrega das issues do front-end, seja por falta de tempo, ou falta de organização, além do que a equipe está um pouco enferrujada em relação a l
A review está boa (sincera) mas tem alguns erros ortográficos, em relação a -> em relação à (Note que esse erro ocorre duas vezes)
tudo foi entrego -> tudo foi entregue

2022-03-17 01:04 UTC, RcleydsonR requested changes
Faltou uma parte da correção ortográfica

2022-03-17 01:04 UTC, RcleydsonR commented on docs/sprints/review_4.md
> +- Nessa Sprint houve bastante dificuldade em relação à entrega das issues do front-end, seja por falta de tempo, ou falta de organização, além do que a equipe está um pouco enferrujada em relação à l
Faltou consertar a parte do "tudo foi entrego" para "tudo foi entregue"

2022-03-17 01:22 UTC, RcleydsonR approved these changes
Ótimo, parabéns pelo documento!

2022-03-17 01:23 UTC, merged