Aplicação GoFs criacionais
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #124
Opened 2022-03-17 02:37 UTC by RcleydsonR

## Descrição

Criação do documento referente a aplicação dos padrões GoFs criacionais no backend do projeto.

## Está consertando alguma issue aberta?

#118 

## Tarefas gerais realizadas
- Adição da aplicação do Factory Method e Builder

2022-03-18 13:53 UTC, thiagohdaqw commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +| 1.1    | 16/03/2022 | Adição da aplicação de Builder | João Moura e Rafael Ramos              |
versão 1.2

2022-03-18 13:57 UTC, thiagohdaqw commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +<p align="justify" style="text-indent: 20px">A metodologia utilizada para a elaboração do documento consistiu na reunião dos membros responsáveis por esta tarefa via discord, onde foram levantados al
pequeno erro de concordancia em "serão demonstrad**o**s dois"

2022-03-18 23:39 UTC, brenno-silva requested changes
Em relação ao conteúdo está excecente, bom trabalho pessoal. Só coloquei algumas observações de formatação.

2022-03-18 23:39 UTC, brenno-silva commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +<p align="justify" style="text-indent: 20px">Após estudo dos padrões GOFs criacionais, iremos demonstrar como eles podem ser aplicados no nosso contexto de estudo do backend, isso é, utilizando Pytho
Quais seriam esses fatores?

2022-03-18 23:39 UTC, brenno-silva commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +<p align="justify" style="text-indent: 20px">A metodologia utilizada para a elaboração do documento consistiu na reunião dos membros responsáveis por esta tarefa via discord, onde foram levantados al
```suggestion
<p align="justify" style="text-indent: 20px">A metodologia utilizada para a elaboração do documento consistiu na reunião dos membros responsáveis por esta tarefa via discord, onde foram levantados alguns padrões de GoF's criacionais encontrados ou não no código desenvolvido para o projeto. Sendo assim, serão demonstradas dois padrões de projetos, sendo eles: <i>Factory Method</i> e <i>Builder</i>. Vale ressaltar que o documento está sujeito a atualizações caso o grupo sinta necessidade de apresentar novos padrões, ou até mesmo atualizar os já existentes.</p>
```

2022-03-18 23:39 UTC, brenno-silva commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +<p align="justify" style="text-indent: 20px">A <i>Abstract Factory</i> é um padrão de projeto criacional que através de herança e polimorfismo permitem às classes herdarem métodos que serão implement
Opcional, mas seria interessante uma linkagem para o documento de estudo no `<i>Abstract Factory</i>`

2022-03-18 23:39 UTC, brenno-silva commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +<p align="justify" style="text-indent: 20px">O <i>Builder</i> é um padrão de projeto criacional que permite a instanciação de um objeto complexo através de uma simples solicitação, mantendo todo o pr
Opcional, mas seria interessante uma linkagem para o documento de estudo no `<i>Builder</i> `

2022-03-19 01:04 UTC, Joao-Moura commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +<p align="justify" style="text-indent: 20px">Após estudo dos padrões GOFs criacionais, iremos demonstrar como eles podem ser aplicados no nosso contexto de estudo do backend, isso é, utilizando Pytho
Também não sei kkkkkkk. O que o sono não faz

2022-03-19 01:17 UTC, brenno-silva approved these changes
Tudo ok.

2022-03-19 11:30 UTC, thiagohdaqw requested changes

2022-03-19 11:30 UTC, thiagohdaqw commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +<p align="justify" style="text-indent: 20px">A metodologia utilizada para a elaboração do documento consistiu na reunião dos membros responsáveis por esta tarefa via discord, onde foram levantados al
```suggestion
<p align="justify" style="text-indent: 20px">A metodologia utilizada para a elaboração do documento consistiu na reunião dos membros responsáveis por esta tarefa via Discord, onde foram levantados alguns padrões de GoF's criacionais encontrados ou não no código desenvolvido para o projeto. Sendo assim, serão demonstrados dois padrões de projetos, sendo eles: <i>Abstract Factory</i> e <i>Builder</i>. Vale ressaltar que o documento está sujeito a atualizações, caso o grupo sinta necessidade de apresentar novos padrões, ou até mesmo atualizar os já existentes.</p>
```

2022-03-19 11:30 UTC, thiagohdaqw commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +| 1.3.1  | 18/03/2022 | Correções de texto | João Moura |
```suggestion
| 1.3.1  | 18/03/2022 | Correções de texto | João Moura |
| 1.3.2  | 19/03/2022 | Revisão por pares | Brenno e Thiago |
```

2022-03-19 11:30 UTC, thiagohdaqw commented on docs/padroes_projetos/aplicacao/gofs_criacionais.md
> +| 1.1    | 16/03/2022 | Adição da aplicação de Factory Method        | João Moura e Rafael Ramos                   |
```suggestion
| 1.1    | 16/03/2022 | Adição da aplicação do Abstract Factory        | João Moura e Rafael Ramos                   |
```

2022-03-19 13:38 UTC, thiagohdaqw approved these changes
Bom trabalho

2022-03-19 17:27 UTC, merged