Aplicação GOFS Comportamentais
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #126
Opened 2022-03-18 13:09 UTC by thiagohdaqw

## Descrição

Criação do documento referente a aplicação dos padrões GoFs comportamentais.

## Está consertando alguma issue aberta?

- #123 

## Tarefas gerais realizadas
- Adição da aplicação do State
- Adição da aplicação do Memento
- Adição da aplicação do Observer

2022-03-18 22:55 UTC, Joao-Moura requested changes
Parabéns pelo trabalho galera. Encontrei 2 errinhos simples e gostaria de ressaltar que os padrões State e Memento não possuem modelagem, sendo necessário adicionar (como foi feito em UML para o Observer) para os respectivos GoF's.

2022-03-18 22:55 UTC, Joao-Moura commented on docs/padroes_projetos/aplicacao/gofs_comportamentais.md
> +<p align="justify" style="text-indent: 20px">Utilizando o Flutter, podemos perceber que a navegação a partir das interfaces do app é realizada utilzando o padrão de <i>Memento</i>. A partir de uma pi
```suggestion
<p align="justify" style="text-indent: 20px">Utilizando o Flutter, podemos perceber que a navegação a partir das interfaces do app são realizadas utilzando o padrão de <i>Memento</i>. A partir de uma pilha de memória, onde os estados das páginas vão sendo armazenados e restaurados quando for necessário.</p>
```

2022-03-18 22:55 UTC, Joao-Moura commented on docs/padroes_projetos/aplicacao/gofs_comportamentais.md
> +<p align="justify" style="text-indent: 20px">Em nosso projeto, há a necessidade de cadastrar um técnico e realizar diversas tarefas após isso. Como mostra a Figura 8, pode-se utilizar o padrão <i>Obs
```suggestion
<p align="justify" style="text-indent: 20px">Em nosso projeto, há a necessidade de cadastrar um técnico e realizar diversas tarefas após isso. Como mostra a Figura 8, pode-se utilizar o padrão <i>Observer</i> para que diversas tarefas, como enviar um e-mail, SMS ou notificar a Emater, sejam executadas assim que um técnico é cadastrado. Desta forma, são possíveis serem adicionadas novas tarefas de forma simples e eficiente</p>
```

2022-03-19 22:19 UTC, Joao-Moura approved these changes
Show, parabéns galera

2022-03-21 01:20 UTC, CarlosFiuza approved these changes
Ótimo trabalho pessoal, a explicação da aplicação dos padrões ficou muito boa.

2022-03-21 02:21 UTC, merged