128 padrao emergente
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #129
Opened 2022-03-19 12:25 UTC by Denniel-sudo

## Descrição
Criação e demonstração de alguns padrões emergentes do projeto com exemplos implementados 

## Está consertando alguma issue aberta?
#128 

## Tarefas gerais realizadas
- [x] Escolha de um padrão entre os anteriormente levantados
- [x] Criação do documento
- [x] Criação de exemplo
- [x] Explicação e exemplificação com o projeto

2022-03-19 13:15 UTC, RcleydsonR requested changes
Excelente documento galera, porém não vejo necessidade de ter todo o texto de estudo novamente, visto que os documentos já estão separados justamente para facilitar quando quisermos ver somente a aplicação, só gostaria que apagassem essa parte teórica e deixassem apenas a parte relevante, tirando isso não encontrei nenhum outro erro :)

2022-03-19 13:15 UTC, RcleydsonR commented on docs/padroes_projetos/aplicacao/padrao_emergente.md
> +- **Client-Server (Cliente-Servidor):** Sempre há um cliente e um servidor e esses dois sistemas precisam de limites para o funcionamento.
Acredito que essa explicação toda não é necessária visto que já temos ela no estudo desses padrões, esse documento deve estar mais focado na aplicação no projeto, sendo assim, somente o último parágrafo é  interessante.

2022-03-19 13:16 UTC, RcleydsonR commented
Lembrando também de dois aspectos importantes, o primeiro commit está errado referenciado a issue #125 ao invés da #128... E também é interessante melhorar o título do Pull request, let's boraa!

2022-03-19 13:26 UTC, RcleydsonR commented on docs/padroes_projetos/aplicacao/padrao_emergente.md
> +- **Client-Server (Cliente-Servidor):** Sempre há um cliente e um servidor e esses dois sistemas precisam de limites para o funcionamento.
O último parágrafo é interessante porque explica como o conceito é aplicado no projeto, e não toda a parte teórica do conceito.

2022-03-19 17:41 UTC, Joao-Moura requested changes
Parabéns pelo trabalho pessoal, apenas umas pequenas correções textuais.

2022-03-19 17:41 UTC, Joao-Moura commented on docs/padroes_projetos/aplicacao/padrao_emergente.md
> +<p align="justify" style="text-indent: 20px">Após estudo dos padrões emergentes, iremos demonstrar como eles podem ser aplicados no contexto projeto, isso é, utilizando Flutter, desenvolvido em Dart,
```suggestion
<p align="justify" style="text-indent: 20px">Após estudo dos padrões emergentes, iremos demonstrar como eles podem ser aplicados no contexto do projeto, isso é, utilizando Flutter, desenvolvido em Dart, e Django REST Framework, desenvolvido em Python, de forma que os padrões podem ser aplicados a fim de colaborarem com um melhor desenvolvimento de código e padronização desses fatores.</p>
```

2022-03-19 17:41 UTC, Joao-Moura commented on docs/padroes_projetos/aplicacao/padrao_emergente.md
> +<p align="justify" style="text-indent: 20px">Assim como mostrado na Figura 1, temos o flutter como <i>client</i> principal do nosso sistema, sendo que, por meio do Django REST Framework foi desenvolv
```suggestion
<p align="justify" style="text-indent: 20px">Assim como mostrado na Figura 1, temos o flutter como <i>client</i> principal do nosso sistema, sendo que, por meio do Django REST Framework foi desenvolvida a API RESTful do nosso projeto. A transmissão entre <i>client</i> e REST API é feita inicialmente por meio de um JSON, com o XML também podendo ser necessário, a medida que forem aparecendo dados mais complexos a serem transmitidos.</p>
```
Acredito que assim tenha ficado melhor, fica de vocês alterarem ou não.

2022-03-19 17:41 UTC, Joao-Moura commented on docs/padroes_projetos/aplicacao/padrao_emergente.md
> +<p align="justify" style="text-indent: 20px">Já a Figura 2 demonstra o template de como uma requisição funciona na nossa API do projeto. Há uma rota para técnicos e é possivel interagir com ela por m
```suggestion
<p align="justify" style="text-indent: 20px">Já a Figura 2 demonstra o template de como uma requisição funciona na nossa API do projeto. Há uma rota para técnicos em que é possivel interagir com ela por meio dos verbos HTTP e HTTPS, onde os dados do técnico são transmitidos em forma de JSON.</P>
```

2022-03-19 17:41 UTC, Joao-Moura commented on docs/padroes_projetos/aplicacao/padrao_emergente.md
> +<p align="justify" style="text-indent: 20px">A Figura 3 procura mostrar como é feita a comunicação entre <i>client</i> e API REST no projeto, em que através do Dio e pelos verbos HTTP foi utilizado u
```suggestion
<p align="justify" style="text-indent: 20px">Por fim, a Figura 3 procura mostrar como é feita a comunicação entre <i>client</i> e API REST no projeto, em que através do Dio e pelos verbos HTTP e/ou HTTPS foi realizado um POST para cadastrar as informações registradas no client do técnico para a nossa api, sendo a Figura 2 o retorno ao ser concluída a ação. </p>
```

2022-03-20 00:55 UTC, Joao-Moura approved these changes
Show pessoal, parabéns.

2022-03-20 15:33 UTC, RcleydsonR approved these changes
Excelente trabalho galera!

2022-03-20 20:10 UTC, merged