Estilos e Padrões Arquiteturais Parte IV
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #143
Opened 2022-03-23 01:51 UTC by VitorLamego

## Descrição
Realização do estudo relacionado a estilos e padrões arquiteturais com foco em arquitetura orientada a serviços e arquitetura orientada a eventos

## Está consertando alguma issue aberta?
#135 

## Tarefas gerais realizadas
- Realização do Estudo
- Documentação

2022-03-23 03:06 UTC, Joao-Moura requested changes
Parabéns pelo documento, fiz umas sugestões e correções de texto. No mais é isso, ficou show.

2022-03-23 03:06 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">Durante a disciplina, foi definido que a arquitetura de software é responsável por definir a estrutura que será implementada em um determinado software. S
```suggestion
<p align="justify" style="text-indent: 20px">Durante a disciplina, foi definido que a arquitetura de software é responsável por padronizar a estrutura que será implementada em um determinado software. Sabendo disso, iremos abordar alguns pontos importantes relacionados ao Estilo Arquitetural Orientado a Eventos. Para isso, é importante entender que um evento é tudo aquilo que representa uma mudança significativa no estado do software em questão, podendo ter uma origem interna, algum clique por parte do usuário, ou externa com alguma informação recebida do servidor [1]. A principal diferença entre um evento e uma entrada qualquer é que o evento está fora de controle do processo que o manipula. [2]</p>
```

2022-03-23 03:06 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">De forma básica, o seu funcionamento consiste em um evento ser publicado em um determinado barramento ou alguma fila e os serviços que possuem interesse n
```suggestion
<p align="justify" style="text-indent: 20px">De forma básica, o seu funcionamento consiste em um evento ser publicado em um determinado barramento ou alguma fila e os serviços que possuem interesse nesse determinado evento consomem e reagem [3]. Para isso, existem dois diferentes modelos de envetos que são bastante utilizados, e que serão detalhados a seguir: </p>
```

2022-03-23 03:06 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">A partir das explicações dadas e dos estudos feitos, pode-se perceber que existem algumas vantagens na utilização desse determinado estilo arquitetural no
```suggestion
<p align="justify" style="text-indent: 20px">A partir das explicações dadas e dos estudos feitos, pode-se perceber que existem algumas vantagens na utilização desse determinado estilo arquitetural no projeto. Alguns dos benefícios para sua utilização serão listados a seguir: </p>
```

2022-03-23 03:06 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +## 3. Estilo Arquitetural Orientado a Eventos
Aqui vai uma dúvida, os padrões Observer e State (GoF's Comportamentais) não poderiam ser citados como uma arquitetura orientada a eventos ? Se forem, acho massa colocar no texto e linkar os documentos.

2022-03-23 03:06 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">O estilo arquitetural orientado a serviços consiste em um tipo de design em que os componentes são reutilizáveis a partir do uso de algumas interfaces de
```suggestion
<p align="justify" style="text-indent: 20px">O estilo arquitetural orientado a serviços consiste em um tipo de design em que os componentes são reutilizáveis a partir do uso de algumas interfaces de serviços com uma linguagem de comunicação comum em uma rede [4]. Foi a partir dessa nova arquitetura de software que as empresas conseguiram ter um acesso mais democrático e viável a servidores remotos que estão fora da própria organização, além de permitir que as empresas e organizações tornem acessíveis as suas informações para outros programas a partir da publicação de uma interface de WebService [2]. Resumidamente, a arquitetura orientada a serviços integra componentes de software que foram implementados e mantidos separadamente, permitindo que trabalhem juntos para formar aplicações que funcionam em sistemas diferentes [4].</p>
```
Aqui é implantado mesmo ? Ou seria implementado ? Achei que os dois ficaram certos.

2022-03-23 03:06 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">Falando um pouco mais sobre o funcionamento do estilo arquitetural orientado a serviços, a comunicação entre serviços é feita por um sistema de "baixo aco
```suggestion
<p align="justify" style="text-indent: 20px">Falando um pouco mais sobre o funcionamento do estilo arquitetural orientado a serviços, a comunicação entre serviços é feita por um sistema de "baixo acomplamento" o que permite que a conexão entre os seus componentes seja mais simples por não possuírem dependência entre si, também admitindo a reutilização desses mesmos serviços em outros projetos. Antigamente, a cada projeto que se fazia necessário a utilização de serviços era feito um processo complexo de conexão da aplicação que incluía vários processos e fases que davam certo trabalho, também conhecido como modelo monolítico.</p>
```

2022-03-24 00:44 UTC, brenno-silva requested changes
Em relação ao conteúdo, aparenta estar tudo certo, só algumas correções ortográficas.

2022-03-24 00:44 UTC, brenno-silva commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +    <li><b>Escalabilidade</b>: A sua evolução acaba sendo uma tarefa muito simples, além de fornencer uma capacidade de resposta muito melhor para o projeto, aumentando a escalabilidade.</li>
```suggestion
    <li><b>Escalabilidade</b>: A sua evolução acaba sendo uma tarefa muito simples, além de fornecer uma capacidade de resposta muito melhor para o projeto, aumentando a escalabilidade.</li>
```

2022-03-24 00:44 UTC, brenno-silva commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">Conforme conteúdo estudado na disciplina, o assunto de "Estilos e Padrões Arquiteturais" foi divido em algumas partes para melhor divisão e compreensão. S
```suggestion
<p align="justify" style="text-indent: 20px">Conforme conteúdo estudado na disciplina, o assunto de "Estilos e Padrões Arquiteturais" foi dividido em algumas partes para melhor divisão e compreensão. Sendo assim, esse documento é responsável pela documentação dos assuntos vistos na última parte, sendo apresentado o estilo arquitetural orientado a eventos e orientado a serviços.</p>
```

2022-03-28 19:22 UTC, VitorLamego commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">O estilo arquitetural orientado a serviços consiste em um tipo de design em que os componentes são reutilizáveis a partir do uso de algumas interfaces de
É implantados mesmo, mas implementados também tem o seu sentido correto.

2022-03-28 19:40 UTC, brenno-silva approved these changes

2022-03-28 19:51 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte4.md
> +<p align="justify" style="text-indent: 20px">O estilo arquitetural orientado a serviços consiste em um tipo de design em que os componentes são reutilizáveis a partir do uso de algumas interfaces de
Sem problemas, pode manter então

2022-03-28 19:52 UTC, Joao-Moura approved these changes

2022-03-28 19:53 UTC, merged