Estilos e Padrões Arquiteturais Parte 3
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #144
Opened 2022-03-23 02:14 UTC by brenno-silva

## Descrição
Adicionando documento de estudo dos Estilos e Padrões Arquiteturais Parte 3

## Está consertando alguma issue aberta?
- #138 

## Tarefas gerais realizadas
- Criação do documento

2022-03-24 18:37 UTC, Joao-Moura requested changes
Show, parabéns pelo esforço. Apenas algumas pequenas correções

2022-03-24 18:37 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte3.md
> +- **Fonte de dados** **(*****Data source*****)**: Fonte para os dados a serem utilizados
```suggestion
- **Fonte de dados** **(*****Data source*****)**: Fonte dos dados a serem utilizados
```
Aqui não seria dos ?

2022-03-24 18:37 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte3.md
> +<p align="justify" style="text-indent: 20px">O Estilo Repositório consiste nas primeira maneira apresentada, chamada de repositório compartilhado, sendo mais adequada para o compartilhamento de grand
Não entendi o sentido da frase "O Estilo Repositório consiste nas primeira maneira apresentada, chamada de repositório compartilhado", Estilo repositório e repositório compartilhado falam sobre a mesma coisa ?

2022-03-24 18:37 UTC, Joao-Moura commented on docs/arquitetura_reutilizacao/estilos_padroes/parte3.md
> +- Problemas no repositório afeta todos
```suggestion
- Problemas no repositório afetam todos
```
Todos o que ? Seriam os usuários ?

2022-03-24 19:03 UTC, brenno-silva commented on docs/arquitetura_reutilizacao/estilos_padroes/parte3.md
> +<p align="justify" style="text-indent: 20px">O Estilo Repositório consiste nas primeira maneira apresentada, chamada de repositório compartilhado, sendo mais adequada para o compartilhamento de grand
Sim

2022-03-28 00:25 UTC, CarlosFiuza requested changes
Bom trabalho, só deixei um comentário quanto a um erro de sintaxe.

2022-03-28 00:25 UTC, CarlosFiuza commented on docs/arquitetura_reutilizacao/estilos_padroes/parte3.md
> +<p align="justify" style="text-indent: 20px">O Estilo Repositório consiste nas primeira maneira apresentada, também chamada de repositório compartilhado, sendo mais adequada para o compartilhamento d
Aqui "nas" está no plural sendo que deveria estar no singular.
"O Estilo Repositório consiste na primeira maneira..."

2022-03-28 00:30 UTC, Joao-Moura approved these changes

2022-03-28 01:31 UTC, CarlosFiuza approved these changes

2022-03-28 01:32 UTC, merged