Artefato de Storyboard
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #15
Opened 2022-01-29 15:30 UTC by brenno-silva

## Descrição
- Adição do documento de storyboard

## Está consertando alguma issue aberta?
- #6 

## Tarefas gerais realizadas
- Documento de storyboard
- Criação das imagens de storyboard

2022-01-31 21:44 UTC, vital14 commented on docs/requisitos/elicitacao/storytelling.md
> +|RE03|Não funcional|O sistema deve permitir o uso apenas de pessoas já cadastradas em um Instituto de Assistência Técnica e Extensão Rural|
Só não consigo enxergar como os storyboards dizem que apenas quem está cadastrado em um Instituto de Assistência Técnica e Extensão Rural podem usar a aplicação, fora isso, bom trabalho

2022-01-31 23:57 UTC, brenno-silva commented on docs/requisitos/elicitacao/storytelling.md
> +|RE03|Não funcional|O sistema deve permitir o uso apenas de pessoas já cadastradas em um Instituto de Assistência Técnica e Extensão Rural|
Essa parte realmente não ficou bem explícito, vou arrumar a descrição do storyboard 3 para deixar melhor definido a relação entre os personagens.

2022-02-01 13:23 UTC, RcleydsonR requested changes
Muito bom Brenno, gostei muito das abstrações referentes aos Requisitos não funcionais elicitados, mas deixei alguns comentários e também o PR está com conflito, com algumas correções tudo estará no eixo !

2022-02-01 13:23 UTC, RcleydsonR commented on docs/requisitos/elicitacao/storytelling.md
> +<img src="../../../assets/requisitos/elicitacao/storyboard4.png"/>
Essa história ficou um pouco sem sentido no meu ponto de vista, porque se ele não marcou basta cadastrar a colheita visto que esse cadastro terá que ser feito junto a data que ele fornecer, então ele pode cadastrar posteriormente e seria responsabilidade do técnico averiguar esses fatos...
Referente a edição, o produtor não pode editar datas, ele abriria um chamado se tivesse feito algo errado nesse quesito, temos que sempre olhar a partir da segurança da rastreabilidade, creio que deixar a responsabilidade de edição para os técnicos que são os responsáveis por garantir essa rastreabilidade seja um trabalho mais sólido, mas cabe uma discussão de um possível histórico de edições, etc ...

2022-02-01 13:23 UTC, RcleydsonR commented on docs/requisitos/elicitacao/storytelling.md
> +|RE10|Funcional|O produtor deve conseguir editar as informações das culturas|
Esse requisito deriva da história que creio estar equivocada, mas dependendo da nossa discussão não precisa ser alterado..

2022-02-01 13:23 UTC, RcleydsonR commented on docs/requisitos/elicitacao/storytelling.md
> +<p style="text-align: justify; text-indent: 20px"> Boulila, N.; Herrmann A.; Hoffmann A. Using Storytelling to record requirements: Elements for an effective requirements elicitation approach. Fourth
Para manter padronizado poderia retirar essas tags de parágrafo <p> e adicionar um elemento de arquivos md: ">"

2022-02-01 13:23 UTC, RcleydsonR commented on docs/requisitos/elicitacao/storytelling.md
> +<p style="text-align: justify; text-indent: 20px"> Boulila, N.; Herrmann A.; Hoffmann A. Using Storytelling to record requirements: Elements for an effective requirements elicitation approach. Fourth
Esse comportamento deve se repetir para toda a bibliografia

2022-02-01 23:03 UTC, Joao-Moura requested changes

2022-02-01 23:03 UTC, Joao-Moura commented on docs/requisitos/elicitacao/storytelling.md
> +|RE01|Não funcional|A aplicação deve proporcionar uma interface com elementos visuais autoexplicativos|
Trocar RE por ST ou só S para facilitar na rastreabilidade dos requisitos

2022-02-02 02:16 UTC, brenno-silva commented on docs/requisitos/elicitacao/storytelling.md
> +|RE01|Não funcional|A aplicação deve proporcionar uma interface com elementos visuais autoexplicativos|
Editado

2022-02-02 02:16 UTC, brenno-silva commented on docs/requisitos/elicitacao/storytelling.md
> +<p style="text-align: justify; text-indent: 20px"> Boulila, N.; Herrmann A.; Hoffmann A. Using Storytelling to record requirements: Elements for an effective requirements elicitation approach. Fourth
Corrigido

2022-02-02 02:17 UTC, brenno-silva commented on docs/requisitos/elicitacao/storytelling.md
> +<img src="../../../assets/requisitos/elicitacao/storyboard4.png"/>
Realmente foi um equivoco nesse sentido, alterei para uma história referente a marcação da colheita.

2022-02-02 12:18 UTC, Joao-Moura requested changes
Parabéns pelo trabalho, muito bem feito. As únicas coisas que eu peço para mudar são:
- Nos parágrafos utilizar `<p style="text-align: justify; text-indent: 20px">` com os 20px pra a primeira linha não ficar colada na esquerda
- E a segunda é adicionar uma legenda pra tabela de requisitos

2022-02-02 12:27 UTC, Joao-Moura approved these changes
Show, parabéns

2022-02-02 13:04 UTC, RcleydsonR requested changes
Fiz alguns comentários rápidos necessários para a padronização dos documentos !

2022-02-02 13:04 UTC, RcleydsonR commented on docs/requisitos/elicitacao/storytelling.md
> +|ST01|Não funcional|A aplicação deve proporcionar uma interface com elementos visuais autoexplicativos|
Não sei se está sendo assim em todos, mas para padronizar, coloque o tipo de requisito no final da tabela e somente o acrônimo dele -> RF, RNF
tem exemplos em outros códigos se quiser seguir, no de introspecção por exemplo, de restante tá show de bola !

2022-02-02 13:04 UTC, RcleydsonR commented on docs/requisitos/elicitacao/storytelling.md
> +|ST01|Não funcional|A aplicação deve proporcionar uma interface com elementos visuais autoexplicativos|
Além da mudança na tabela também há a necessidade de acrescentar outra tabela para legenda:
ST -> StoryTelling
RF -> Requisito Funcional
RNF -> Requisito Não Funcional

2022-02-02 15:13 UTC, vital14 approved these changes
Bom trabalho!!

2022-02-02 16:35 UTC, brenno-silva commented on docs/requisitos/elicitacao/storytelling.md
> +|ST01|Não funcional|A aplicação deve proporcionar uma interface com elementos visuais autoexplicativos|
Feito

2022-02-02 22:46 UTC, RcleydsonR approved these changes
Excelente Brenno !

2022-02-02 23:45 UTC, merged