#150 Criação do documento de estilos e padrões arquiteturais parte 2
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #151
Opened 2022-03-28 04:11 UTC by Denniel-sudo

## Descrição
Criação do documento de estilos e padrões arquiteturais parte 2

## Está consertando alguma issue aberta?
#150 

## Tarefas gerais realizadas
- [x] Criação do documento
- [x] Explicação dos estilos
- [x] Levantados vantagens e desvantagens

2022-03-28 19:37 UTC, VitorLamego requested changes
Parabéns pelo trabalho !! Deixei apenas algumas correções ortográficas.

2022-03-28 19:37 UTC, VitorLamego commented on docs/arquitetura_reutilizacao/estilos_padroes/parte2.md
> +- Maior facilidade manutenção.
"facilidade de manutenção"

2022-03-28 19:37 UTC, VitorLamego commented on docs/arquitetura_reutilizacao/estilos_padroes/parte2.md
> +-
Remover esse subitem

2022-03-28 19:37 UTC, VitorLamego commented on docs/arquitetura_reutilizacao/estilos_padroes/parte2.md
> +<p align="justify" style="text-indent: 20px">Os protocolos do nível de transporte fornecem serviçoes que garantem uma transferência confiável de dados e aplicativos entre computadores (ou outro equip
Trocar "serviçoes"

2022-03-28 19:37 UTC, VitorLamego commented on docs/arquitetura_reutilizacao/estilos_padroes/parte2.md
> +<p align="justify" style="text-indent: 20px">O protocolo TCP (Transmission Control Protocol) é um protocolo orientado a conexão. Nele, o cliente estabelece uma conexão com o servidor e ambos trocam m
Trocar "quem a termina a sessão"

2022-03-28 22:12 UTC, RcleydsonR commented
Finalizando os erros ortográfico encontrados pelo Lamego e o conflito no arquivo do mkdocs, creio que estará pronto para passar esse PR, senti falta de maior embasamento nas explicações visto que foi boa parte extraída do conteúdo da professora, mas foi um trabalho excelente devido à densidade do conteúdo que torna díficil  sintetizar!

2022-03-30 17:14 UTC, RcleydsonR approved these changes
Excelente trabalho, parabéns!
Não se esqueça de adicionar o campo de revisão por pares :)

2022-03-30 19:21 UTC, VitorLamego approved these changes
Parabéns!!

2022-03-30 19:21 UTC, merged