Artefato Política de Contribuição e configurações diversas do repositório
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #16
Opened 2022-01-29 17:11 UTC by Joao-Moura

## Descrição

- Adição do doc de política de contribuição e configurações extras do repositório

## Está consertando alguma issue aberta?

#13 

## Tarefas gerais realizadas

- Adição do documento de política de contribuição
- Alterando README
- Alterações nos templates

2022-01-29 18:52 UTC, Denniel-sudo approved these changes

2022-01-29 21:51 UTC, RcleydsonR requested changes
Deixei alguns comentários relevantes, no mai, é isso aí, excelente trabalho !

2022-01-29 21:51 UTC, RcleydsonR commented on README.md
> +<p align="justify">&emsp;&emsp; Os dados da caderneta ou plantio são de extrema importância pois nele estão contidas informações cruciais como o produto que foi plantado, onde foi plantado, quais pro
os técnicos que estarão utilizado esse aplicativo" está incorreto, que estarão utilizando*...

2022-01-29 21:51 UTC, RcleydsonR commented on mkdocs.yml
> +        - Ata de Reunião 25/01: reunioes/ata_25_01.md
Que ata de reunião é essa ?

2022-01-29 21:51 UTC, RcleydsonR commented on docs/base/politicas_de_contribuicao.md
> +```bash
Precisa de mais espaço entre as mensagens, senão vai sair tudo bugado, vale a pena verificar no preview do md utilizando o atalho ctrl + shift + v no vs code.

2022-01-29 22:25 UTC, Joao-Moura commented on mkdocs.yml
> +        - Ata de Reunião 25/01: reunioes/ata_25_01.md
Essa parte eu esqueci de fazer mesmo, adicionei pra lembrar e esqueci

2022-01-30 00:57 UTC, RcleydsonR requested changes
Apenas erros gramaticais, coisa rápida !

2022-01-30 00:57 UTC, RcleydsonR commented on docs/reunioes/ata_25_01.md
> +<p align="justify">&emsp;&emsp; Devido ao horário que a reunião foi realizada optou-se por realizar um sprint planning mais simples, ondem apenas ficaram decidas as task da semana e quem estaria real
Palavra errada: "ondem", "decidas"
concordância: task ou tasks ?
Não precisa utilizar task e issue na mesma frase, só referenciar ao que já foi dito:
"onde ficaram decididas as tasks da semana e quem estaria realizando cada uma"

2022-01-30 00:57 UTC, RcleydsonR commented on docs/reunioes/ata_25_01.md
> +<p align="justify">&emsp;&emsp; Após as discuções sobre as metodologias e tasks, partiu-se para a realização do brainstorm, dos mapas mentais e das rich pictures de cada integrante da equipe.</p>
discuções -> discussões

2022-01-30 14:25 UTC, RcleydsonR approved these changes
Excelente João .

2022-01-30 14:26 UTC, merged