Criando documento de Personas
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #19
Opened 2022-01-30 05:07 UTC by PauloAbiAcl

## Descrição 
- Criação do documento de Personas

## Está consertando alguma issue aberta?
- #10 

## Tarefas gerais realizadas
- Documento de Personas
- Adição de imagens das personas

2022-01-31 01:03 UTC, brenno-silva requested changes
Bom trabalho, porém está faltando a referência do documento na sidebar além de algumas outras correções comentadas abaixo:

2022-01-31 01:03 UTC, brenno-silva commented on docs/requisitos/elicitacao/personas.md
> +|<b>Foto:</b>|<p style="text-align: center"><img src="../../assets/requisitos/elicitacao/romao_jose_maria.jpeg" width="200px"></p><p style="text-align: center">Figura 1: Foto de Romão</p><p style="te
As imagens precisam de três "voltas" nas pastas.
Ex: "../../../assets/requisitos/elicitacao/romao_jose_maria.jpeg"

2022-01-31 01:03 UTC, brenno-silva commented on docs/requisitos/elicitacao/personas.md
> +<p style="text-align: justify; text-indent: 20px"> Courage e Baxter (2005) alertam para que se tenham um cuidado na escolha do número de personas elaboradas. É importante representar os principais gr
"um produto que atenda" no lugar de "um produto atenda"

2022-01-31 01:03 UTC, brenno-silva commented on docs/requisitos/elicitacao/personas.md
> +|<b>Expectativas:</b>| Devido a sua dificuldade com a leitura, romão precisa de um aplicativo acessível e que seja simples, para facilitar sua navegação.|
"romão" sem a letra maiúscula no inicio

2022-01-31 01:03 UTC, brenno-silva commented on docs/requisitos/elicitacao/personas.md
> +|<b>Expectativas:</b>|Por ser criança, carlos ainda não ajuda seus pais no controle das plantações, então não teria motivos para usar a aplicação.|
"carlos" escrito com letra minúscula no inicio

2022-01-31 01:03 UTC, brenno-silva commented on docs/requisitos/elicitacao/personas.md
> +<p style="text-align: justify; text-indent: 20px"> Courage e Baxter (2005) alertam para que se tenham um cuidado na escolha do número de personas elaboradas. É importante representar os principais gr
É citado "(Cooper et al., 2014; Pruitt e Adlin, 2006; Cooper, 1999)" e "Courage e Baxter (2005)", porém não consta a fonte nas referências.

2022-02-02 00:23 UTC, CarlosFiuza approved these changes
Ótimo trabalho! Ficou muito bom, parabéns!

2022-02-02 02:30 UTC, brenno-silva approved these changes
Muito bom!

2022-02-02 02:31 UTC, merged