Artefato Elicitacao Brainstorming
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #20
Opened 2022-01-30 15:22 UTC by CarlosFiuza

## Descrição
Criação do documento de Brainstorming

## Está consertando alguma issue aberta?
#5 

## Tarefas gerais realizadas
- Abertura do documento
- Adição do quadro branco e do vídeo
- Elicitação dos requisitos

2022-01-30 19:37 UTC, Joao-Moura requested changes
Citei umas coisinhas pequenas pra alteração, mas de resto é isso. Parabéns pelo doc, muito bem feito.

2022-01-30 19:37 UTC, Joao-Moura commented on docs/requisitos/elicitacao/brainstorming.md
> +- Paulo Vitor
O Paulo não pode estar presente no brainstorm

2022-01-30 19:37 UTC, Joao-Moura commented on docs/requisitos/elicitacao/brainstorming.md
> +<p align="justify" style="text-indent: 20px">Toda a dinâmica foi gravada e está no vídeo abaixo:</p>
Acho que vale a pena ressaltar que o vídeo está sem cortes, na íntegra.

2022-01-30 21:26 UTC, vital14 approved these changes
Além de corrigir o que o joao solicitoi, ajustar os conflitos de merge, fora isso, bom trabalho

2022-01-30 21:33 UTC, Denniel-sudo approved these changes

2022-01-31 11:34 UTC, Joao-Moura approved these changes

2022-01-31 11:37 UTC, merged