Artefato de Introspecção
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #21
Opened 2022-01-30 16:55 UTC by RcleydsonR

## Descrição

&emsp; Foi desenvolvido um documento de elicitações baseado na técnica de introspecção, qualquer sugestão peço que seja incluída nos comentários.

## Está consertando alguma issue aberta?

#11

## Tarefas gerais realizadas
- Descrever a perspectiva do usuário através da introspecção
- Documentar os requisitos levantados
- Formatado o documento de metodologias para padronizar os documentos

2022-01-30 21:36 UTC, vital14 reviewed
Deixei um Comentário apenas, fora isso, um bom trabalho

2022-01-30 21:36 UTC, vital14 commented on docs/base/metodologia.md
> +<p style="text-align: justify; text-indent: 20px"> O SCRUM é uma metodologia ágil muito conhecida e que já até se expandiu para diversas outras áreas além da Engenharia de Software. Focada no planeja
Creio que seria interação e não iteraçao

2022-01-30 23:01 UTC, brenno-silva requested changes
Excelente documento, só é preciso corrigir pequenos erros de escrita.

2022-01-30 23:01 UTC, brenno-silva commented on docs/requisitos/elicitacao/introspeccao.md
> +* O usuário deve poder editar suas informações pessoas.
"Pessoais" em "pessoas"

2022-01-30 23:01 UTC, brenno-silva commented on docs/requisitos/elicitacao/introspeccao.md
> +* O técnico deve pode editar todas as informações, exceto a foto cadastrada.
"Poder" em "pode"

2022-01-30 23:01 UTC, brenno-silva commented on docs/requisitos/elicitacao/introspeccao.md
> +|I13|O produtor deve adcionar a data de colheita encerrando a plantação |RF|
"Adicionar" em "adcionar"

2022-01-30 23:01 UTC, brenno-silva commented on mkdocs.yml
> +    - Módulo Projeto Não Orientado a Abordagens Específicas:
Não seria melhor deixar a área de "iniciativas extras" como o tópico final na sidebar?

2022-01-31 02:16 UTC, RcleydsonR commented on docs/base/metodologia.md
> +<p style="text-align: justify; text-indent: 20px"> O SCRUM é uma metodologia ágil muito conhecida e que já até se expandiu para diversas outras áreas além da Engenharia de Software. Focada no planeja
Agradeço demais o feedback Vital, porém o termo correto é mesmo iteração com o sentido de ser um ciclo de repetição e acúmulo de experiências, onde a iteração é conhecida como sprint, ficou claro ?

2022-01-31 02:34 UTC, RcleydsonR commented on mkdocs.yml
> +    - Módulo Projeto Não Orientado a Abordagens Específicas:
Creio que essa seja uma boa solução, vou aplicar !

2022-01-31 02:35 UTC, RcleydsonR commented on docs/requisitos/elicitacao/introspeccao.md
> +|I13|O produtor deve adcionar a data de colheita encerrando a plantação |RF|
fixed

2022-01-31 02:35 UTC, RcleydsonR commented on docs/requisitos/elicitacao/introspeccao.md
> +* O técnico deve pode editar todas as informações, exceto a foto cadastrada.
fixed

2022-01-31 02:35 UTC, RcleydsonR commented on docs/requisitos/elicitacao/introspeccao.md
> +* O usuário deve poder editar suas informações pessoas.
fixed

2022-01-31 10:52 UTC, brenno-silva approved these changes
Tudo certo.

2022-01-31 20:30 UTC, vital14 approved these changes
Tudo ok! Bom trabalho

2022-01-31 20:30 UTC, merged