Artefato do Termo de Abertura de Projeto (TAP)
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #22
Opened 2022-01-30 21:24 UTC by Joao-Moura

## Descrição

- Adição do termo de abertura de projeto junto com documentos sobre riscos e custos.

## Está consertando alguma issue aberta?

#4 

## Tarefas gerais realizadas
- Adição do Termo de Abertura de Projeto (TAP)
- Adição do documento de Riscos
- Adição do documento de Custos (WIP)

2022-02-01 03:00 UTC, brenno-silva requested changes
O escopo do documento está bem completo, fiz apenas algumas observações

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; Esse documento tem como principal objetivo formalizar o início do projeto informando os estudos de viabilidade, prazos e entregas, orçamentos, objetivos e os riscos pa
"construção" em "contrução"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; Dentro da gerência de um projeto de software, um dos pontos essênciais é realizar a gestão de riscos do produto. Com esse controle, é possível a equipe entender, lista
"essenciais" em "essênciais"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +- Cliente: Diz respeito à critério de aceitação dos clientes desde etapas inicias de elicitação de requisitos até a utilização diária da aplicação.
"ao critério" em "à critério"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +- Depêndencias de Projeto: Se refere à possíveis riscos advindo de depêndencias utilizadas dentro do projeto, sendo aplicável também aos riscos técnicos.
"Dependências" em "Depêndencias"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +- Priorização: Riscos influênciados pelo cliente e possíveis priorizações equivocadas dos requisitos.
"influenciados" em "influênciados"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +- Desempenho: Diretamente relacionados à velocidade e eficiência da aplicação construida.
"construída" em "construida"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +|Indiponibilidade de um integrante por doença|Moderado|Provável|Buscar sempre atender as prevenções para o Covid-19 e a nova gripe H3N2|Alocação de membros para as issues que ficarem desfalcadas|9|
"Indisponibilidade" em "Indiponibilidade"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +|Falhas de comunicação entre a equipe|Elevado|Quase Nulo|Utilizar formas de engajar e aumentar a comunicação entre a equipe|Alocar issues em pares e usar atividades de enganjamento|4|
"engajamento" em "enganjamento"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; Seguindo, portanto, a modelagem do COCOMO parte-se agora para o cálulo da estimativa de esforço. Pelas características do projeto e pelo modo intermediário ter sido es
"cálculo" em "cálulo"

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +|Indiponibilidade de um integrante por doença|Moderado|Provável|Buscar sempre atender as prevenções para o Covid-19 e a nova gripe H3N2|Alocação de membros para as issues que ficarem desfalcadas|9|
Além de alocar membros, fazer a revisão do escopo do projeto para se adequar a indisponibilidade de integrantes seria uma adição válida, já que não necessariamente haverão outros membros disponíveis.

2022-02-01 03:00 UTC, brenno-silva commented on docs/base/termo_de_abertura.md
> +|Desistência de integrante da matéria|Alto|Pouco Provável|Manter motivação dos membros sempre alta e uma boa gerência de equipe|Realocação das issues para os membros restantes|10|
A mesma observação feita no "Indisponibilidade de um integrante por doença" seria válida nesse caso.

2022-02-01 11:13 UTC, brenno-silva approved these changes
Muito bom!

2022-02-01 14:01 UTC, RcleydsonR reviewed
Deixei um comentário sobre o tópico de Objetivos, aguardo discussão complementar para continuar o review, mas desde já, quero elogiar a confecção deste documento que com certeza deu um belo trabalho, você é show !

2022-02-01 14:01 UTC, RcleydsonR commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; O objetivo principal é construir um aplicativo que um <a href=#produtor>produtor</a> possa estar utilizando para realizar o <a href=#envio_fotos>envio de fotos</a> de
Me deixou um pouco confuso esse tópico de objetivo principal, está sendo enaltecido um aplicativo para que um produtor possa utilizar pra enviar fotos pra promover toda a rastreabilidade, mas creio que o objetivo principal é promover a rastreabilidade através da confecção de uma caderneta de campo digital, onde aí sim entram os papéis dos técnicos (validam) e dos produtores (preenchem), a questão da foto é um príncipio de boa usabilidade e acessibilidade do app que ajudará os produtores a preencher dados mais complicados, porém é um meio para um fim e não o fim de fato !

2022-02-01 21:02 UTC, Joao-Moura commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; O objetivo principal é construir um aplicativo que um <a href=#produtor>produtor</a> possa estar utilizando para realizar o <a href=#envio_fotos>envio de fotos</a> de
Bem notado Rafael, revisei o documento e refiz os tópicos de objetivos e justificativas para se enquadrar com o tema e o escopo do nosso projeto

2022-02-02 00:06 UTC, RcleydsonR requested changes
Caramba, documento está fantástico, destaquei apenas alguns erros ortográficos mas fora isso tá ótimo !

2022-02-02 00:06 UTC, RcleydsonR commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; O objetivo principal é construir um aplicativo que um <a href=#produtor>produtor</a> possa estar utilizando para realizar a confecção de sua <a href=#cardeneta_de_camp
através da ajuda através do envio de fotos ?

2022-02-02 00:06 UTC, RcleydsonR commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; Uma das ferramentas utilizadas para gerir os riscos desse projeto é a Estrutura Analítica de Riscos (EAR), que corresponde a uma ferramenta de agrupamento e organizaçã
visualizer -> visualizar

2022-02-02 01:20 UTC, Joao-Moura commented on docs/base/termo_de_abertura.md
> +<p align="justify">&emsp;&emsp; Uma das ferramentas utilizadas para gerir os riscos desse projeto é a Estrutura Analítica de Riscos (EAR), que corresponde a uma ferramenta de agrupamento e organizaçã
english please 🙄

2022-02-02 01:23 UTC, RcleydsonR approved these changes
Termo muito bem documentado, parabéns pelo trabalho !

2022-02-02 01:31 UTC, merged