Artefato do 5W2H
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #24
Opened 2022-01-30 23:53 UTC by VitorLamego

## Descrição
Foi adicionado o documento referente à aplicação da técnica 5W2H com o projeto.

## Está consertando alguma issue aberta?
#23 

## Tarefas gerais realizadas
- Resumo da técnica
- Aplicação da técnica
- Referências Bibliográficas

2022-01-31 00:47 UTC, brenno-silva requested changes
Apenas pequenas correções na escrita, em questão de conteúdo está muito bom!

2022-01-31 00:47 UTC, brenno-silva commented on docs/base/5W2H.md
> +<p align = 'justify'> &emsp;&emsp; O processo de rastreabilidade dos produtos agrícolas já é feito a partir da Caderneta de Campo, contudo, como o objetivo de facilitar e até mesmo automatizar alguns
A letra maiúscula em "facilitando" e "trabalho" no lugar de "trablhando"

2022-01-31 00:47 UTC, brenno-silva commented on docs/base/5W2H.md
> +<p align = 'justify'> &emsp;&emsp; O objetivo com este documento é contextualizar melhor a equipe e os stakeholders envolvidos no que se refere às informações básicas do aplicativo em questão. A técn
"Softwarem" e "Brasílila"

2022-01-31 00:47 UTC, brenno-silva commented on docs/base/5W2H.md
> +<p align = 'justify'> &emsp;&emsp; O projeto será desenvolvido de Fevereiro de 2022 até Junho de 2022, podendo se extender caso os alunos envolvidos queiram dar continuidade ao projeto, mesmo após en
"Estender" em "extender"

2022-02-02 12:34 UTC, brenno-silva requested changes

2022-02-02 12:34 UTC, brenno-silva commented on docs/base/5W2H.md
> +<p align = 'justify'> &emsp;&emsp; [1] 5W2H. Disponível em: <a href="https://jrconsultoria.com.br/5w2h/" target="_blank">https://jrconsultoria.com.br/5w2h</a>. Acesso em: 10 de agosto de 2021 </p>
Seguindo a recomendação do Rafael, seria interessante padronizar as referências utilizando um `> ` em vez do `<p align = 'justify'>`

2022-02-04 01:48 UTC, brenno-silva requested changes
Ficou mais padronizado o texto, mas ainda possuiu alguns pontos para correção

2022-02-04 01:48 UTC, brenno-silva commented on mkdocs.yml
> +    - Iniciativas Extras:
Esse "iniciativas extras" jogado quebra o mkdocs

2022-02-04 01:48 UTC, brenno-silva commented on docs/base/5W2H.md
> +<p style="text-align: justify; text-indent: 20px"> [1] 5W2H. Disponível em: <a href="https://jrconsultoria.com.br/5w2h/" target="_blank">https://jrconsultoria.com.br/5w2h</a>. Acesso em: 10 de agosto
Referências continuam sem estar padronizadas

2022-02-04 12:03 UTC, brenno-silva approved these changes
Tudo certo, bom documento!

2022-02-04 12:06 UTC, PauloAbiAcl approved these changes
Bom trabalho!!

2022-02-04 12:10 UTC, merged