Create diagrama de causa e efeito
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #25
Opened 2022-01-31 12:26 UTC by Denniel-sudo

## Descrição
Foi criado documento referente ao problema a ser resolvido com a aplicação proposta 

## Está consertando alguma issue aberta?

#8 

## Tarefas gerais realizadas
- Introdução
- Descrição sobre a metodologia utilizada
- Criação do diagrama

2022-01-31 13:07 UTC, Joao-Moura requested changes
Parabens pelo documento, bem interessante. Eu acredito que ainda seria possível encontrar mais e especificar melhor os processos, mas isso fica por você.
No mais é isso, deixei uns comentários de padronização e correção ortográfica.

2022-01-31 13:07 UTC, Joao-Moura commented on docs/requisitos/elicitacao/diagrama_causa_efeito.md
> +O diagrama de causa e efeito, também conhecido como Diagrama de Ishikawa, tem como fundamento discutir possíveis causas de um problema. Ele é sendo dividido em diversos processos, e em cada processo
- "Ele é sendo dividido..." para "Ele é dividido..."
- "processo levantando" para "processo levantado"
- Repetição da palavra processo, tentar trocar por sinônimos
- Usar a formatação padrão do repositório com parágrafos justificados (da uma olhada nos docs que já foram aprovados)

2022-01-31 13:07 UTC, Joao-Moura commented on docs/requisitos/elicitacao/diagrama_causa_efeito.md
> +* [Ferramentas de qualidade: Diagrama de Ishikawa(Causa e Efeito). Canal: Aprendendo Gestão](https://www.youtube.com/watch?v=U-0qzmFqH-0&t=2s)
- Alterar Referências Bibliográficas para apenas Bibliografia
- Formatar da mesma forma que os demais docs do repositório (da uma olhadinha que nos outros docs também tem essa parte de referência)

2022-02-03 17:36 UTC, Joao-Moura approved these changes
Parabéns pelo doc, só achei estranho porque seu doc trouxe um monte de commit do merge, mas acho que isso não vai dar problema na master.

2022-02-03 21:40 UTC, CarlosFiuza approved these changes
Bom trabalho!

2022-02-03 22:14 UTC, merged