Artefato de Rich Picture
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #29
Opened 2022-01-31 23:44 UTC by oEduardoAfonso

## Descrição

Foi criada a página para documentar o processo de implementação do artefato rich picture no projeto.

## Está consertando alguma issue aberta?

#1 

## Tarefas gerais realizadas

- Criação dos rich pictures individuais
- Escolha do rich picture principal
- Documento de pré-elicitação Rich Picture

2022-02-01 00:35 UTC, thiagohdaqw requested changes, later dismissed
Trabalho muito bem feito, parabens!
Abaixo deixo alguns comentários sobre a padronização do documento

2022-02-01 00:35 UTC, thiagohdaqw commented on docs/base/requisitos/pre-rastreabilidade/rich-picture.md
> +&emsp;&emsp; Rich picture é um artefato visual simples, que permite fazer anotações rápidas sobre ideias que surgem durante debates e reuniões. É usado comumente como uma forma de rascunho, sendo alt
Fonte?

2022-02-01 00:35 UTC, thiagohdaqw commented on docs/base/requisitos/pre-rastreabilidade/rich-picture.md
> +&emsp;&emsp; O grupo optou por utilizar o artefato como uma forma de elucidar as ideias dos membros sobre o conceito geral do produto que se planeja desenvolver. Após realizar um [Brainstorm](https:/
Colocar os parágrafos como justificados por questao de padronização
Pode usar o `<p style="text-align: justify; text-indent: 20px"> TEXTO </p>`

2022-02-02 18:22 UTC, oEduardoAfonso commented on docs/base/requisitos/pre-rastreabilidade/rich-picture.md
> +&emsp;&emsp; Rich picture é um artefato visual simples, que permite fazer anotações rápidas sobre ideias que surgem durante debates e reuniões. É usado comumente como uma forma de rascunho, sendo alt
Adicionei o tópico de bibliografia e fiz referência ao material utilizado.

2022-02-02 18:23 UTC, oEduardoAfonso commented on docs/base/requisitos/pre-rastreabilidade/rich-picture.md
> +&emsp;&emsp; O grupo optou por utilizar o artefato como uma forma de elucidar as ideias dos membros sobre o conceito geral do produto que se planeja desenvolver. Após realizar um [Brainstorm](https:/
Adicionado parágrafo justificado aos textos.

2022-02-02 18:27 UTC, RcleydsonR requested changes
Só uma alteração na nomenclatura dos arquivos, sugiro resolver quando for resolver os conflitos

2022-02-02 18:27 UTC, RcleydsonR commented on mkdocs.yml
> +          - Rich Picture: base/requisitos/pre-rastreabilidade/rich-picture.md
Quando estiver corrigindo os conflitos, padronize também a nomenclatura dos arquivos com os separadores sendo o "_" underline

2022-02-02 18:42 UTC, oEduardoAfonso commented on mkdocs.yml
> +          - Rich Picture: base/requisitos/pre-rastreabilidade/rich-picture.md
Alterei o nome da pasta de pré rastreabilidade para o padrão da branch principal e também troquei o "-" por "_" no nome do arquivo.

2022-02-03 00:13 UTC, CarlosFiuza approved these changes
Bom trabalho!

2022-02-03 14:20 UTC, RcleydsonR requested changes
Commits estão formatados de maneira errada, de acordo com a política de contribuição  eles devem apresentar o número base da issue. Ex:
#4 Corrigindo documento de planejamento

2022-02-04 01:05 UTC, RcleydsonR approved these changes
Excelente Dudu, mto obg pela dedicação

2022-02-04 01:07 UTC, merged