Criação do documento de Sprint Review 0 e Sprint Planning 1
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #50
Opened 2022-02-08 21:27 UTC by Joao-Moura

## Descrição

- Adição das documentações sobre a review e o planning das sprints 0 e 1

## Está consertando alguma issue aberta?

#49 

## Tarefas gerais realizadas

- Adição do documento de review 0
- Adição do documento de planning 1
- Modificação do mkdocs

2022-02-08 23:02 UTC, thiagohdaqw requested changes
Documento muito bom, parabéns!
Só deixo alguns comentários aqui em baixo

2022-02-08 23:02 UTC, thiagohdaqw commented on docs/sprints/review_0.md
> +## Visão Geral
Por questão de padronização, acho interessante colocar os índices de cada topico

## 1. Visão Geral
## 2. Conclusões

2022-02-08 23:02 UTC, thiagohdaqw commented on mkdocs.yml
> +      - Iniciativas Extras:
As iniciativas extras acabou ficando dentro do Projeto Orientado a Abordagens Tradicionais
Correção:
- Modelagem
    - Projeto Orientado a Abordagens Tradicionais:
        - ...
    - Iniciativas Extras:
        - ....

2022-02-08 23:33 UTC, thiagohdaqw approved these changes

2022-02-09 12:41 UTC, brenno-silva approved these changes
Bom trabalho João!

2022-02-09 12:42 UTC, merged