Criação do documento de Diagrama de Classes
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #53
Opened 2022-02-11 12:37 UTC by thiagohdaqw

## Descrição
Foi desenvolvido o documento de modelagem estática "Diagrama de Classes", responsável por descrever as classes e os seus respectivos relacionamentos evidenciando a camada de domínio do backend.

## Está consertando alguma issue aberta?
#44 

## Tarefas gerais realizadas
-  Descrição do que é Diagrama de Classes
- Confecção do Diagrama de Classes

2022-02-11 16:47 UTC, Joao-Moura requested changes
Parabéns pelo doc, muito interessante a diagramação feita. Tenho uns pontos que eu gostaria de discutir e já padronizar isso:
1 - As classes, atributos e métodos vão ter nomes em inglês ? Na minha visão seria mais interessante elas serem em portugues por conta do nosso léxico.
2 - O relacionamento _wait_ entre _Cultivation_ e _Pesticide_ não tem direção mesmo ? É uma linha em vez de uma seta ?

No mais é isso, só identifiquei um erro de ortografia e espero o feedback de vocês

2022-02-11 16:47 UTC, Joao-Moura commented on docs/modelagem/estatica/diagrama_de_classes.md
> +<p align="justify" style="text-indent: 20px">Diagramas de classes fazem parte de um dos seis tipos de diagrama estrutural em UML (Unified Modeling Language), tem por objetivo modelar a estrutura está
"seis tipos de diagrama estrutural ..." para "seis tipos de diagramas estruturais"

2022-02-12 00:20 UTC, Joao-Moura approved these changes
Show de bola

2022-02-13 15:46 UTC, Denniel-sudo approved these changes

2022-02-13 15:55 UTC, merged