#54 adicionando documento e diagrama de componentes
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #56
Opened 2022-02-14 06:58 UTC by vital14

## Descrição
Criação do documento e do diagrama de componentes

## Está consertando alguma issue aberta?
#54 

## Tarefas gerais realizadas
- [ ] Pesquisa e descrição do diagrama de componentes
- [ ] Criação do diagrama de componentes no escopo do projeto
- [ ] Adição do documento com descrição e o diagrama

2022-02-14 20:55 UTC, Joao-Moura approved these changes
Aprovado, só achei meio simplório o diagrama mas parabéns pelo trabalho galera

2022-02-14 21:08 UTC, RcleydsonR requested changes
Apenas um erro ortográfico rápido, mas o trabalho tá top.

2022-02-14 21:08 UTC, RcleydsonR commented on docs/modelagem/estatica/diagrama_de_componentes.md
> +<p align="justify" style="text-indent: 20px">O Diagrama de componentes é criado em UML e tem como função representar os componentes que pertencem a um sistema e como eles se comunicam entre si, para
seviço -> serviço

2022-02-14 22:03 UTC, RcleydsonR commented
Um questionamento, vamos ter usuário "Administrador" ?

2022-02-15 11:33 UTC, Joao-Moura approved these changes
Agora sim o diagrama ficou show, parabéns galera.

2022-02-15 11:33 UTC, Joao-Moura commented on docs/modelagem/estatica/diagrama_de_componentes.md
> +> [2] **UML – Diagramas Estruturais Diagrama de Componentes**. Disponível em: <a href="http://www.facom.ufu.br/~flavio/swmod-files/files/2015-02/11-UML-Diagramas-Compoentes-e-Implantacao-Pacotes.pdf"
Só uma dúvida, essa referência foi usada diretamente em algum lugar no texto ? Se não tiver sido acho válido criar o tópico `##5. Bibliografia` e colocar ele lá

2022-02-15 12:01 UTC, RcleydsonR commented on docs/modelagem/estatica/diagrama_de_componentes.md
> +> [2] **UML – Diagramas Estruturais Diagrama de Componentes**. Disponível em: <a href="http://www.facom.ufu.br/~flavio/swmod-files/files/2015-02/11-UML-Diagramas-Compoentes-e-Implantacao-Pacotes.pdf"
No final da introdução ele utiliza uma indicação à referência [1].

2022-02-15 12:01 UTC, RcleydsonR approved these changes
Melhorou bastante o diagrama pessoal, muito bom !

2022-02-15 12:58 UTC, merged