Criação do documento de modelagem ágil NFR Framework
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #66
Opened 2022-02-15 15:32 UTC by Joao-Moura

## Descrição

- Adição do doc de modelagem ágil pelo NFR Framework

## Está consertando alguma issue aberta?

#62 

## Tarefas gerais realizadas

- Adição de introdução sobre o tema
- Adição dos diagramas NFR
- Adição dos diagramas NFR propagados

2022-02-15 21:05 UTC, RcleydsonR requested changes
Eu realmente curti muito as operacionalizações levantadas nesse documento, vai ser de extrema importância para o desenvolvimento. Coloquei alguns erros ortográficos no review. Senti um pouco de falta dos relacionamentos AND e OR entre os softgoals descendentes e ascendentes, mas com uma boa leitura dá para entender!

2022-02-15 21:05 UTC, RcleydsonR commented on docs/modelagem/agil/nfr_framework.md
> +<p style="text-align: justify; text-indent: 20px">Essa metodologia de modelagem tem como principal objetivo decompor os requisitos não funcionais a niveis operacionas. Dessa maneira, facilita-se a co
niveis operacionas -> níveis operacionais

2022-02-15 21:05 UTC, RcleydsonR commented on docs/modelagem/agil/nfr_framework.md
> +<p style="text-align: justify; text-indent: 20px">Diversas técnicas podem ser utilizadas para a análise e modelagem dos requisitos funcionais, porém poucas delas são capazes de realizar essa função d
dentro dos requisitos não funcionais -> nos requisitos não funcionais

2022-02-15 21:05 UTC, RcleydsonR commented on docs/modelagem/agil/nfr_framework.md
> +#### 4.1.1 Sem progpagação
progpagação -> propagação

2022-02-15 21:05 UTC, RcleydsonR commented on docs/modelagem/agil/nfr_framework.md
> +#### 4.2.1 Sem progpagação
progpagação -> propagação

2022-02-15 21:05 UTC, RcleydsonR commented on docs/modelagem/agil/nfr_framework.md
> +#### 4.3.1 Sem progpagação
progpagação -> propagação

2022-02-15 21:05 UTC, RcleydsonR commented on docs/modelagem/agil/nfr_framework.md
> +#### 4.4.1 Sem progpagação
progpagação -> propagação

2022-02-15 21:13 UTC, VitorLamego commented on docs/modelagem/agil/nfr_framework.md
> +#### 4.2.1 Sem progpagação
Corrigir "Progpagação"

2022-02-15 21:14 UTC, VitorLamego commented on docs/modelagem/agil/nfr_framework.md
> +#### 4.1.1 Sem progpagação
Corrigir o subtítulo "progpagação", também vale para os itens 4.2.1, 4.3.1 e 4.4.1

2022-02-15 21:17 UTC, VitorLamego commented on docs/modelagem/agil/nfr_framework.md
> +<h6 align = "center">Figura 2: SIG de usabilidade com propagaçao</h6>
Faltando acento em "propagaçao"

2022-02-15 21:27 UTC, VitorLamego requested changes
Parabéns pelo documento e pela aplicação da metodologia, os diagramas ficaram muito bem elaborados. Pontuei alguns pequenos erros a serem corrigidos no texto e gostaria de deixar dois pontos de observação, ficando ao seu critério se irá mudar ou não, mas que no meu ponto de vista melhoram o documento

1. As imagens dos elementos de propagação não estão alinhadas com a legenda. Parece que algumas imagens são maiores que outras. Vou deixar uma imagem para mostrar como está sendo apresentado para mim.

![Captura de tela de 2022-02-15 18-12-11](https://user-images.githubusercontent.com/54643464/154151872-dd0694b8-52fd-49d7-a08f-c1446bcf38d8.png)


2. Os diagramas estão com a classe "zoom", só que nesse caso eu achei ruim na hora de olhar, algumas vezes eu passava o mouse por cima para acompanhar certo elemento a e a imagem dava esse zoom que não ajudava na visualização, na verdade até atrapalhava um pouco. Além disso a legenda da imagem fica por cima do diagrama. Enfim, achei que o zoom atrapalhou um pouco nesse caso.

2022-02-16 03:02 UTC, RcleydsonR requested changes
Ficou faltando somente um erro ortográfico, se quiser seguir a sugestão do Lamego e centralizar as imagens com css também, fique a vontade.

2022-02-16 03:02 UTC, RcleydsonR commented on docs/modelagem/agil/nfr_framework.md
> +<p style="text-align: justify; text-indent: 20px">Essa metodologia de modelagem tem como principal objetivo decompor os requisitos não funcionais a níveis operacionas. Dessa maneira, facilita-se a co
operacionas -> operacionais

2022-02-16 12:07 UTC, RcleydsonR approved these changes
Agora está show, belíssimo trabalho, parabéns !

2022-02-16 19:04 UTC, VitorLamego approved these changes
Parabéns pelo trabalho!

2022-02-16 19:06 UTC, merged