Criação do Diagrama de Sequência
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #68
Opened 2022-02-16 13:11 UTC by brenno-silva

## Descrição
Adição do documento de diagrama de sequência.

## Está consertando alguma issue aberta?
#63 

## Tarefas gerais realizadas
- Correção dos links do product backlog
- Criação do documento de diagrama de sequência

2022-02-16 13:38 UTC, PauloAbiAcl requested changes
Excelente trabalho, corrigir apenas o erro ortográfico apresentado logo abaixo.

2022-02-16 13:38 UTC, PauloAbiAcl commented on docs/assets/modelagem/diagramaSequencia2.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:lucid="lucid" width="2040" height="1240"><g transform="translate(-240 -180)" lucid:page-tab-id="0_0"><path d="
No tópico 1.4 tem um erro ortográfico, está escrito planrtio.

2022-02-16 14:24 UTC, Joao-Moura approved these changes
Parabéns pelo trabalho pessoal só deixei uma sugestão, fiquem a vontade para acatarem ou não.

2022-02-16 14:24 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_sequencia.md
> +<p align="justify" style="text-indent: 20px">Para a realização dos diagramas foi utilizada a ferramenta online LucidChart.</p>
Acredito ser válido linkar o LucidChart ao site oficial usando a tag `<a href>`.

2022-02-17 14:02 UTC, PauloAbiAcl approved these changes
Só resolver os conflitos, no mais tudo certo!!

2022-02-17 14:48 UTC, merged