Criação do diagrama de comunicação
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #74
Opened 2022-02-18 03:32 UTC by Joao-Moura

## Descrição
Adição da documentação sobre o diagrama de comunicação.

## Está consertando alguma issue aberta?
#61 

## Tarefas gerais realizadas
- Adição de explicação sobre a metodologia
- Criação de quatro diagramas de comuncação sobre o projeto

2022-02-18 13:03 UTC, thiagohdaqw requested changes
Bom trabalho, galera, gostei muito do que foi apresentado!
Contudo, tenho algumas dúvidas em relação ao diagrama

2022-02-18 13:03 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<p align="justify" style="text-indent: 20px">Esse modelo de diagrama corresponde à "uma forma simplificada dos diagramas de sequência sem os mecanismos de estruturação" [1]. Além disso, essa diagrama
"[...] interação entre **objectos** de um projeto[...]" 
objectos -> objetos

2022-02-18 13:03 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<p align="justify" style="text-indent: 20px">Esse modelo de diagrama corresponde à "uma forma simplificada dos diagramas de sequência sem os mecanismos de estruturação" [1]. Além disso, essa diagrama
"[..] essa diagramação conforme Clair [2], visa [...]"
tem uma virgula aqui depois de diagramação, nao?
"[..] essa **diagramação, conforme** Clair [2], visa [...]"

2022-02-18 13:03 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Algumas dúvidas em relação a essa interação:
Toda vez que o produtor colher uma plantação, deveria ser registrada uma caderneta de campo para que se possa rastrear esse produto gerado.
Sendo assim, a geração da caderneta de campo não deveria ser disparada a partir do colhimento de uma plantação?
Por exemplo, uma versão simplista:

![image](https://user-images.githubusercontent.com/54081877/154687237-f06022d4-8afa-4e11-94e3-ce17f2a7c7ad.png)

2022-02-18 13:03 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Eu pessoalmente gosto de imagem com fundo branco, pois quando dá o zoom nao confunde com o fundo, mas é pessoal mesmo

2022-02-18 13:03 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao2.svg" class="zoom"/>
Nesse caso aqui, no talhão, será feito uma plantação(Plantio) e para isso é necessario da informação da cultura. A aplicação do agrotóxico é gerada a partir da plantação e não da cultura, como especificado no diagrama

![image](https://user-images.githubusercontent.com/54081877/154687288-e920545e-647d-4cdb-a64c-bcd66d452059.png)

2022-02-18 13:03 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao4.svg" class="zoom"/>
O técnico não deveria iteragir com a aplicação de agrotóxico, visto que é la que tem a foto?

2022-02-18 15:35 UTC, RcleydsonR requested changes
Muito bem galera, trabalho top! Complementei algumas correções do Thiago  e deixei algumas dúvidas nos diagramas também.

2022-02-18 15:35 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<p align="justify" style="text-indent: 20px">Dentre os muitos diagramas de interação - aqueles que mostram a interação entre objetos e/ou partes - que são possíveis de serem representados através da
Ao invés de usar um hífen não seria melhor separar essa definição com uma vírgula?

2022-02-18 15:35 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<p align="justify" style="text-indent: 20px">Como já citado, o diagrama de comunicação é uma forma simplificada do diagrama de sequência, porém ao contrário deste, realiza a modelagem do tempo de aco
através de um enumeração -> através de uma enumeração ou por uma enumeração

2022-02-18 15:35 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Também tive esse mesmo pensamento. Após gerada a caderneta podem ser consultadas algumas informações que vão estar no histórico da propriedade, mas julgo ser uma interação com a propriedade.

2022-02-18 15:35 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Concordo, não gostei desse zoom com fundo transparente, nesse caso seria melhor não ter.

2022-02-18 15:35 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao3.svg" class="zoom"/>
Não entendi a condição do existe talhão quando ele consulta propriedade, o talhão é criado quando ele cadastra a propriedade a partir dos números de talhões, essa poderia ser uma mensagem com a condição "existe plantação", que seria válida para plantações antigas ou atuais.

2022-02-18 15:35 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao4.svg" class="zoom"/>
Também fiquei com essa mesma dúvida, possível correção:
Figura se chamar Interação Técnico
E dentro dela ter a interação do técnico com outros objetos tipo a propriedade e a aplicação.
Se acreditarem que vai fugir demais do padrão, podem seguir com a criação de outra interação simplificada Técnico -> Aplicação

2022-02-18 15:37 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<p align="justify" style="text-indent: 20px">Dentre os muitos diagramas de interação - aqueles que mostram a interação entre objetos e/ou partes - que são possíveis de serem representados através da
Tanto faz, acredito que usar o travesão da um destaque maior

2022-02-18 21:07 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Compreensível, porém a ideia principal desse diagrama foi representar a interaçãod e um produtor com a caderneta de campo. A ideia seria que ao gerarCaderneta() é assumido que foi colhida a plantação.
O que a gente pode estar fazendo é adicionar um texto extra fora do diagrama explixcando esse fluxo, já que no diagrama a interação entre produtor e :CadernetaCampo deve ser direta.

2022-02-18 21:07 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Correção será feita com o merge do pr do Carlinhos.

2022-02-18 21:09 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao2.svg" class="zoom"/>
Acredito não ser necessário, pois a gente fez a abstração de :Cultura sendo aquela que envolve o Plantio. Por mim, isso adicionaria apenas um objeto a mais com mais relacionamentos que chegam no mesmo lugar.

2022-02-18 21:12 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao4.svg" class="zoom"/>
A gente não entendeu muito bem esse comentário, já que a ideia do relacionamento :Propriedade -> :Agrotóxico é em relação à foto enviada por um produtor. Se puderem especificar mais a dúvida pra gente, eu agradeceria.

2022-02-18 21:18 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao3.svg" class="zoom"/>
Faz sentido, optamos por retirar a validação desse relacionamento já que também não é necessário existir plantação para se checar um histórico de um talhão.

2022-02-18 21:34 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Se a conexão é entre o produtor e caderneta, então a partir da caderneta deveria ter uma ligação com Plantio, Cultura, AplicacaoAgrotoxio, Agrotoxico, Talhao e, por fim, propriedade. A caderneta não tem ligação direta com a Cultura, Talhao, Agrotóxico nem propriedade.

2022-02-18 21:35 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao1.svg" class="zoom"/>
Mas se tem essa abstração, entao seria bom colocar na legenda

2022-02-18 21:40 UTC, thiagohdaqw commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao2.svg" class="zoom"/>
Sim, chegaria no mesmo lugar, mas essa é a ideia, diagramar todos os objetos e como interagem para realizar uma determinada funcionalidade.

2022-02-19 20:12 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao2.svg" class="zoom"/>
A condição 1.1 [Plantio colhido] para consultar plantio não devia ser antes no "gerarCaderneta" ? @Joao-Moura @PauloAbiAcl, já que a caderneta só é gerada quando o plantio é colhido.

2022-02-19 20:26 UTC, Joao-Moura commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao2.svg" class="zoom"/>
Não necessariamente, porque ele chama a função de gerarCaderneta que vai validar se teve o plantio colhido na interação com o :Plantio.

2022-02-19 20:34 UTC, RcleydsonR commented on docs/modelagem/dinamica/diagrama_de_comunicacao.md
> +<img src="../../../assets/modelagem/dinamica/diagramaComunicacao4.svg" class="zoom"/>
Suponho que a aplicação de agrotóxico está mais ligada as plantações e essa seria a interação correta, porque o produtor não interage necessariamente com uma propriedade para identificar agrotóxico, ele não identifica o agrotóxico aplicado em uma propriedade porque lá podem ter vários, identifica de uma plantação que pertence a um talhão que aí sim pertence a uma propriedade, creio que vcs subiram demais nessa cadeia de interação, conseguiu entender? Se não concordar por mim, pode ser uma solução também.

2022-02-19 22:13 UTC, RcleydsonR approved these changes
Excelente trabalho galera, creio que nós conseguimos alinhar bastante os pensamentos, então foi um PR muito proveitoso!

2022-02-20 13:24 UTC, thiagohdaqw approved these changes
bom trabalho

2022-02-20 13:28 UTC, merged