Criação do Diagrama Lógico de Dados
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #79
Opened 2022-02-19 00:13 UTC by thiagohdaqw

## Descrição
Adição da documentação sobre o diagrama lógico de dados tomando como base o mer e os tipos especificados no diagrama de classes.

## Está consertando alguma issue aberta?
- #70 

## Tarefas gerais realizadas
- Criação do diagrama
- Documentação do diagrama

2022-02-19 17:59 UTC, oEduardoAfonso requested changes
Ótimo trabalho Thiago.

Achei o documento bem escrito e o diagrama bem feito. Só encontrei um pequeno erro de gramática.

2022-02-19 17:59 UTC, oEduardoAfonso commented on docs/modelagem/extras/dld.md
> +<p align="justify" style="text-indent: 20px">O Diagrama Lógico de Dados pertence ao modelo lógico que representa os bancos de dados como um conjunto de relações [1]. Dessa forma, é possível utilizar
Neste parágrafo está escrito "de um Bancos de Dados Relacional" quando deveria estar escrito "de um Banco de Dados Relacional".

Com "banco" no singular.

2022-02-20 17:48 UTC, PauloAbiAcl requested changes
Excelente documento!!! Só corrigir o conflito, e tenho um pequeno questionamento, que na verdade é mais uma dúvida, não seria necessário a presença de talhão no diagrama?

2022-02-20 18:19 UTC, thiagohdaqw commented
> Excelente documento!!! Só corrigir o conflito e tenho um pequeno questionamento, que na verdade é mais uma dúvida, não seria necessário a presença de talhão no diagrama?
@PauloAbiAcl 

Criar uma entidade talhão faria sentido sim, no entanto, pela entrevista, o numero do talhão é algo simbolico para o produtor se localizar, então não teria muitos atributos. Penso que há duas maneiras de representar essa entidade TALHAO:

- TALHAO (**idPropriedade**, **numeroTalhao**) : Sendo os dois chaves primárias, uma vez que pode ser registrado na forma (1, 1), (1, 2), (2, 1), (2, 2).... Além disso, uma entidade apenas com chaves primarias nao seria uma boa pratica, porque haveria repetição de todos os atributos dessa entidades nos relacionamentos. Mas estaria normalizado.
- TALHAO (**idTalhao**, idPropriedade numeroTalhao) Também funcionaria, mas idPropriedade e numeroTalhao deveria ser unica, pois sao chaves candidatas. Também adicionaria uma maior complexidade para uma entidade simples, como na outra opção.

A adição de uma nova entidade é algo complexo, visto que teria que ocorrer mudanças tanto no MER, DER, DLD, Dicionario de Dados e Diagrama de Classes, mas funcionaria sim. Entao, acho que deveria ser analisado em uma issue separada, visto que essa nao teria escopo para isso, pois se baseia no MER que ja foi validado antes.

No modelo que está, sem uma entidade TALHAO, também funciona, pois é possivel agrupar os PLANTIOs por meio de um GROUP BY numeroTalhao.

2022-02-20 18:32 UTC, PauloAbiAcl approved these changes
Obrigado pelo esclarecimento Thiago, Tudo certo então.

2022-02-20 20:12 UTC, oEduardoAfonso approved these changes
Tudo certo. Parabéns pelo trabalho.

2022-02-20 20:36 UTC, merged