71 documento de caso de uso
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #82
Opened 2022-02-20 18:08 UTC by Denniel-sudo

## Descrição
Implementação dos casos de uso do projeto

## Está consertando alguma issue aberta?
#71 

## Tarefas gerais realizadas
- [x] Criação da especificação de caso de uso

2022-02-20 18:33 UTC, thiagohdaqw commented
Opa, denniel, ainda nao revisei.
Para evitar conflitos, acho que seria bom atualizar essa branch, pois ela ta bem desatualizada com a master e contém commits relacionados a outros documentos

2022-02-20 19:58 UTC, thiagohdaqw requested changes
Trabalho muito bem feito, parabens!
Encontrei alguns problemas que detalho mais abaixo.
Recomendo sempre testar rodando o mkdocs `mkdocs serve` para ver se nao quebrou nada.
E também colar o texto no google docs para checar a ortografia do documento.
No mais foi isso, ficou muito bom, mano

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +# Casos de Uso
Faltou o link desse documento no `mkdocs.yml`. Sem ele, nao aparece no site

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +<p style="text-align: justify; text-indent: 20px">Os diagramas de caso de uso tem por objetivo auxiliar na modelagem, demonstrando o comportamento do sistema e ajudam a capturar seus requisitos. Eles
Acredito que nesse trecho "[...] demonstrando o comportamento do sistema e **ajudam** a capturar seus requisitos. [..]"
o ajudam seja ajudando
"[...] demonstrando o comportamento do sistema e **ajudando** a capturar seus requisitos. [..]"

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +<p style="text-align: justify; text-indent: 20px">Os diagramas de caso de uso tem por objetivo auxiliar na modelagem, demonstrando o comportamento do sistema e ajudam a capturar seus requisitos. Eles
Aqui em `</p>.` tem um ponto depois do fechamento da tag. Quando abre no mkdocs esse ponto fica no meio da tela.
![image](https://user-images.githubusercontent.com/54081877/154861117-c5eed8a9-bb69-4736-bfff-2de220d95d5f.png)

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +|0.1|16/02/2022|Abertura do documento de casos de uso|Denniel William|
O padrão do versionamento é começar em 1.0

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +<p style="text-align: justify; text-indent: 20px">Os diagramas de caso de uso tem por objetivo auxiliar na modelagem, demonstrando o comportamento do sistema e ajudam a capturar seus requisitos. Eles
em "[...] nível de **usuário mas** não descreve [...]" tem uma virgula antes do mas

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +> [1] **Diagrama de caso de uso UML: O que é, como fazer e exemplos**. Lucidchart. Disponível em: <a href="https://www.lucidchart.com/pages/pt/diagrama-de-caso-de-uso-uml" target="_blanck">https://ww
Ja que utilizou referencias, seria bom colocar a citação no texto

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +![Diagrama de caso de uso](/docs/assets/requisitos/modelagem/diagrama_de_caso_de_uso.jpg)
Esse link para imagem está quebrado. Recomendo usar a tag img com class zoom pra melhorar a visualização. O caminho certo seria:

`<img src="../../../assets/modelagem/diagrama_de_caso_de_uso.jpg" class="zoom"/>`

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +<p style="text-align: center; text-indent: 20px"><strong>Figura 1: Casos de Uso do Caderneta de Campo Digital.<br/>Fonte: Autoria própria</strong></p>.
normalmente o formato das fontes é

`<h6 align = "center">Figura 1: SIG de usabilidade</h6>`
`<h6 align = "center">Fonte: Autor</h6>`

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +<p style="text-align: center; text-indent: 20px"><strong>Figura 1: Casos de Uso do Caderneta de Campo Digital.<br/>Fonte: Autoria própria</strong></p>.
pequeno problema de concordancia na fonte "[...] Casos de Uso **do** Caderneta de Campo [...]"
deveria ser **da Caderneta**

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +|Pós-condições| O ator poderá ter acesso as funcionalidades do seu tipo de <a href="/requisitos/modelagem/lexicos#usuario">usuário</a> logado|
acredito que tenha uma crase em "[...] ter acesso **as** funcionalidade [...]"

2022-02-20 19:58 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +### UC18 Alterar plantação
A partir desse caso de uso, as tabelas estão quebradas
![image](https://user-images.githubusercontent.com/54081877/154861743-320392fa-1950-4044-9cea-41fa9cdacc25.png)

2022-02-20 20:00 UTC, thiagohdaqw commented on docs/modelagem/extras/caso_de_uso.md
> +<p style="text-align: center; text-indent: 20px"><strong>Figura 1: Casos de Uso do Caderneta de Campo Digital.<br/>Fonte: Autoria própria</strong></p>.
Acho que as tabelas tbm deveriam ter fontes

2022-02-21 11:08 UTC, thiagohdaqw approved these changes

2022-02-21 11:14 UTC, CarlosFiuza approved these changes
Muito bom !

2022-02-21 11:20 UTC, merged