Customização wiki
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #83
Opened 2022-02-21 11:07 UTC by CarlosFiuza

## Descrição
Adição de uma landing page, mudança na fonte e estilo das tabelas da wiki

## Está consertando alguma issue aberta?
#81 

## Tarefas gerais realizadas
- Adição de uma landing page
- Mudança na fonte
- Aplicação de estilo das tabelas da wiki

2022-02-23 11:04 UTC, brenno-silva commented on docs/index.html
> +          <h5 class="button-text" >Documentação</h5>
O zoom quando passa por cima do botão faz o texto ficar pequeno para o tamanho ocupado.

2022-02-23 11:04 UTC, brenno-silva commented on docs/index.html
> +  <section id="section-1" class="container max-height">
Esse alinhamento ficou estranho, parece que "Cadernata de Campo" está alinhada a esquerda, o botão passando um pouco do centro e os outros dois estão centralizados.
![image](https://user-images.githubusercontent.com/54643530/155306573-f015f7fc-5969-4cda-a81e-10c6d4d1d0cf.png)

2022-02-23 11:05 UTC, brenno-silva requested changes
O novo visual ficou muito bacana, só alguns pontos na landing page para dar uma olhada.

2022-02-23 11:39 UTC, RcleydsonR commented on docs/index.html
> +          <h5 class="button-text" >Documentação</h5>
Além disso, a palavra "Documentação" não está alinhada ao centro do botão

2022-02-23 11:59 UTC, RcleydsonR requested changes
Achei sensacional as mudanças Carlinhos, principalmente considerando nossa identidade visual que está sendo respeitada nessa customização. Porém, complementei o comentário do Brenno e queria relatar outra estranheza por aqui:
![image_2022-02-23_08-37-34](https://user-images.githubusercontent.com/74625814/155315065-4265aa1c-165f-4ca1-8c94-b3aff47b7d97.png)
O top-header ficou transparent com o gradient e os textos ao fundo estão sendo mostrados, achei isso mto estranho porque tem o botão de search que acaba ficando em cima de um monte de palavras/imagens.

2022-02-24 12:29 UTC, CarlosFiuza commented on docs/index.html
> +          <h5 class="button-text" >Documentação</h5>
a ideia do botão é apenas dele expandir sua área quando passar o mouse encima, não incluindo nessa expansão o texto.

2022-02-24 13:22 UTC, brenno-silva requested changes
Pequeno detalhe:

2022-02-24 13:22 UTC, brenno-silva commented on docs/index.html
> +      <h2 id="project-info-2" class="mt-2 text-gradient" >Aplicação Mobile</h2>
"ArqDsw-2021.2" e "Aplicação Mobile" ficaram um pouco apagados, talvez a fonte branca fique melhor.

2022-02-24 16:25 UTC, RcleydsonR approved these changes
Agora ficou top demais Carlos! Excelente trabalho, o ponto a corrigir do Brenno vai de escolha sua, para mim das duas maneiras ficariam okay!

2022-02-25 13:14 UTC, CarlosFiuza commented on docs/index.html
> +      <h2 id="project-info-2" class="mt-2 text-gradient" >Aplicação Mobile</h2>
Tornei o gradiente dessas duas infos mais escuro, assim não aparentam mais estar apagados.

2022-02-26 13:01 UTC, brenno-silva approved these changes
Trabalho muito bom!

2022-02-26 13:55 UTC, merged