Documentação review sprint 2 e planning sprint 3
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #90
Opened 2022-02-22 12:13 UTC by CarlosFiuza

## Descrição
Documentação do ritual de review da sprint 2 e do ritual de planning da sprint 3

## Está consertando alguma issue aberta?
#87 

## Tarefas gerais realizadas
- Documentação review
- Documentação planning

2022-02-22 15:26 UTC, Joao-Moura requested changes
Show de mais os documentos, só deixei umas pequenas correções. Parabéns pelo trabalho

2022-02-22 15:26 UTC, Joao-Moura commented on docs/sprints/planning_3.md
> +| [#67](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/67) | Protótipo de alta fidelidade | 8 |
Eu acredito que em vez de débito poderia colocar Issues em Andamento (2 sprints), algo desse tipo. Isso porque essa task foi planejada para durar 2 sprints então não seria débito.

2022-02-22 15:26 UTC, Joao-Moura commented on docs/sprints/planning_3.md
> +# Sprint 2 - Planning
```suggestion
# Sprint 3 - Planning
```

2022-02-22 21:00 UTC, Joao-Moura approved these changes
Boa

2022-02-23 11:11 UTC, brenno-silva approved these changes
Bons documentos!

2022-02-23 12:03 UTC, merged