92 padroes projetos emergentes
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #94
Opened 2022-02-26 02:03 UTC by Denniel-sudo

## Descrição
Criado os padrões emergentes do projeto, englobando design patterns a serem seguidos como algumas peculiaridades de arquitetura da tecnologia escolhida para o projeto.

## Está consertando alguma issue aberta?
#92 

## Tarefas gerais realizadas
- Criação do documento
- Padronização do documento
- Padrões emergentes do projeto listados e explicados

2022-02-26 17:16 UTC, Joao-Moura requested changes
Primeiramente, parabêns pelo trabalho galera. Agora partindo para as reclamações kkkkkk.
- Achei o documento bem simples
- Duas técnicas repetidas dos padrões de GOF's Criacionais
- Documento não possui o tópico de "Metodologia", conforme foi definido na última review
- Seria legal adicionar umas imagens para contextualizar melhor (é claro, se vocês acharem)
- Erros pontuais citados abaixo

Acredito que é isso, sugiro uma refatoração do documento ou apenas dos tópicos mencionados. Novamente, parabéns pelo trabalho e vamo que vamo.

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">Padrões de projeto são formatos de soluções que são utilizadas de forma recorrente dentro do projeto. Esses padrões são comumente utilizados em projetos c
Não entendi a frase "... Orientado a Objeto, sendo bastante, tranformando ...", ficou estranho esse sendo bastante junto com o transformando

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">Os padrões nomeados como emergentes são derivados da necessidade de algum fator específico para utilizar determinada solução. Portanto, os padrões emergen
```suggestion
<p align="justify" style="text-indent: 20px">Os padrões nomeados como emergentes são derivados da necessidade de algum fator específico para utilizar determinada solução. Portanto, os padrões emergentes são definidos quando possuímos um determinado comportamento inerente ao padrão, contudo não possuimos a estrutura que o descreve, o que é muito comum em situações como: falta de conhecimento por parte do desenvolvedor sobre os padrões de projetos, sucessivas mudanças em outras classes que então são refletida em uma determinada parte do código, falta de refatoração, característica do problema e, então, não necessita implementar o padrão.[1]</p>
```
Além disso, a frase "... e, então, não necessita implementar o padrão.[1]" ficou sem sentido para mim.

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">Existindo uma determinada classe A, se esta for um Singleton, em qualquer momento de execução essa classe pode ter apenas zero ou uma instância dessa clas
Se formos seguir o definido pela professora, Singleton é considerado um GOF Criacional. Rever esse tópico.

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">O baixo acoplamento é importante para facilitar a manutenibilidade do código, além de permitir a utilização de mocks para realizar testes unitários nas re
O baixo acoplamento é gerado da injeção de dependência ? Se sim, explicar melhor porque ficou bem solto esse parágrafo.

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">O padrão de Factory Method é utilizado quando temos um método m que é responsável por retornar um objeto do tipo T, que podem, a qualquer momento, serem i
Factory Method assim como os Singletons são padrões de GOF's criacionais. Um dos principais é exatamente o factory method. Rever esse parágrafo.

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">O padrão de Rest ou Restful, Representational State Transfer (Transferência de Estado Representacional), define a padronização de rotas, requisições e com
O padrão não é REST ou RESTful. Ele utiliza a uma filosofica RESTful para aplicar o padrão REST (conforme explicação do @thiagohdaqw no dojo de django).

```suggestion
<p align="justify" style="text-indent: 20px">O padrão de REST ou RESTful, Representational State Transfer (Transferência de Estado Representacional), define a padronização de rotas, requisições e comunicações sem estado, também conhecico como protocolo HTTP. Sendo assim, o padrão REST define de utilizar desse protocolo sendo que a API que possui a inteligência de aplicar esse padrão ela tem termo atribuído como Restful.[1]</p>
```

Ficou sem sentido a frase "... o padrão REST define de utilizar desse protocolo sendo que a API que ...".

O número dessa referência está certo ? Todos vem da 1, sendo que existem 5 referência citadas ?

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">Um dos padrões também que serão seguidos, será o MVT, em que por ter sido de opção da equipe a utilização do framework Django, o padrão a ser utilizado se
```suggestion
<p align="justify" style="text-indent: 20px">Um dos padrões que também serão seguidos, será o MVT, em decorrência da utilização do framework Django, definido pela equipe para o backend</p>
```
Tentei dar uma melhorada nesse parágrafo, porque ele ficou bem repetitivo sem acrescentar muitas informações ao tópico.

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">O padrão MVT se baseia na distribuição de Model, View e Template: A model atua como a interface de dados, ela é a estrutura lógica por trás do aplicativo
```suggestion
<p align="justify" style="text-indent: 20px">O padrão MVT se baseia na distribuição de Model, View e Template: A model atua como a interface de dados, ela é a estrutura lógica por trás do aplicativo e é representado pelo banco de dados do projeto; A view é usada para executar as regras de negócios, interação com o modelo para transporte de dados e renderização do template; O template é a camada de apresentação, e é responsável pela parte da interface do usuário.</p>
```
Esse texto tem alguma referência ? Porque se não, seria bom botar. Além disso, a gente não vai estar utilizando todo o MVT, a princípio, o frontend vai ser o responsável pela camada de "template".

2022-02-26 17:16 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +> [5] **Entendendo o MTV do Django**. Entendendo o MTV do Django. Disponível em: <a href="https://www.treinaweb.com.br/blog/entendendo-o-mtv-do-django" >Entendendo o MVT do Django</a>. Acesso em: 25
Dessas 5 referências, só vi 2 serem utilizadas. Ou foram citadas referências não utilizadas, ou elas não foram referênciadas corretamente nos textos.

2022-02-27 14:47 UTC, Denniel-sudo commented
> Primeiramente, parabêns pelo trabalho galera. Agora partindo para as reclamações kkkkkk.
> 
> * Achei o documento bem simples
> * Duas técnicas repetidas dos padrões de GOF's Criacionais
> * Documento não possui o tópico de "Metodologia", conforme foi definido na última review
> * Seria legal adicionar umas imagens para contextualizar melhor (é claro, se vocês acharem)
> * Erros pontuais citados abaixo
> 
> Acredito que é isso, sugiro uma refatoração do documento ou apenas dos tópicos mencionados. Novamente, parabéns pelo trabalho e vamo que vamo.

é realmente necessário um tópico de metologia? pq ao que aparenta essa parte do documento apresenta a própria peculiaridade de cada projeto e certos padrões que são próprios da tecnologia e etc. Tanto que a Milene criou um tópico de debate e soltou só um áudio de 1 minuto e 30 segundos para explicar isso.

2022-02-27 15:04 UTC, Joao-Moura requested changes
Show, agora o documento ficou bem melhor. Achei uns errinhos pontuais e pedi a review.
Em relação ao tópico de metodologia, ele é para ser algo simples sobre como esse artefato em si foi produzido. Foi reunião no discord ? Foi feito separadamente ? Coisas assim, apenas para melhorar a rastreabilidade da produção dele.

2022-02-27 15:04 UTC, Joao-Moura commented on mkdocs.yml
> +    - Padrões emergentes: padroes_projetos/padroes_emergentes.md
Padronizar as pastas para o seguinte formato:
```yml
  - Padrões de Projeto:
    - Estudos:
      - GOFs Criacionais: padroes_projetos/estudos/gofs_criacionais.md (esse daqui ta em outra branch)
      - Padrões emergentes: padroes_projetos/estudos/padroes_emergentes.md (cololcar dentro da pasta estudos)
```

2022-02-27 15:04 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +- **Cacheable (Armazenável com cache):** Os clientes precisam ser capazes de armazenar em cache as representações. Devido à ausência de estado (toda representação sendo autodescritiva), isso é possív
Aqui como já foi citado o [5] no parágrafo de introdução, pode tirar a numeração de cada tópico

2022-02-27 15:04 UTC, Joao-Moura commented on docs/padroes_projetos/padroes_emergentes.md
> +<img src="../../../assets/padroes_projeto/rest.png" width="800"/>
Centralizar essa e a imagem abaixo

2022-02-27 15:07 UTC, Denniel-sudo commented on mkdocs.yml
> +    - Padrões emergentes: padroes_projetos/padroes_emergentes.md
> Show, agora o documento ficou bem melhor. Achei uns errinhos pontuais e pedi a review. Em relação ao tópico de metodologia, ele é para ser algo simples sobre como esse artefato em si foi produzido. Foi reunião no discord ? Foi feito separadamente ? Coisas assim, apenas para melhorar a rastreabilidade da produção dele.

No documento está explicado sobre a reunião, que no caso foram discussões pelo telegram (que está explicado lá o meio tbm)

2022-02-27 15:21 UTC, Joao-Moura commented on mkdocs.yml
> +    - Padrões emergentes: padroes_projetos/padroes_emergentes.md
Eita verdade, eu passei pelo tópico e nem vi. Desculpa kkkk.

2022-02-27 15:21 UTC, Joao-Moura approved these changes
Parabéns pelo esforço pessoal.

2022-02-27 21:45 UTC, RcleydsonR requested changes
Parabéns galera, no geral estão muito bem explicados esses padrões, já tive a oportunidade de trabalhar com alguns então curti muito a explicação, deixei alguns erros ortográficos presentes no texto e uma correção as imagens que estão quebradas, mas reforço o meu agradecimento ao trabalho feito !

2022-02-27 21:45 UTC, RcleydsonR commented on docs/padroes_projetos/estudos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">Padrões de projeto são formatos de soluções que são utilizadas de forma recorrente dentro do projeto. Esses padrões são comumente utilizados em projetos c
tranformando -> transformando

2022-02-27 21:45 UTC, RcleydsonR commented on docs/padroes_projetos/estudos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">Os padrões nomeados como emergentes são derivados da necessidade de algum fator específico para utilizar determinada solução. Portanto, os padrões emergen
possuimos -> possuímos
que então são ? Acho que seria: "que são então", ou somente "que são", e a concordância está errada também (mudanças refletidos)

2022-02-27 21:45 UTC, RcleydsonR commented on docs/padroes_projetos/estudos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">Injeção de dependência é um padrão utilizado para dimimuir o acoplamento de determinada parte do código, que costuma acontecer quando uma classe depende d
dimimuir -> diminuir

2022-02-27 21:45 UTC, RcleydsonR commented on docs/padroes_projetos/estudos/padroes_emergentes.md
> +<p align="justify" style="text-indent: 20px">O baixo acoplamento é importante para facilitar a manutenibilidade do código, além de permitir a utilização de mocks para realizar testes unitários nas re
respecivas -> respectivas

2022-02-27 21:45 UTC, RcleydsonR commented on docs/padroes_projetos/estudos/padroes_emergentes.md
> +  <img src="../../../assets/padroes_projeto/rest.png" width="800"/>
Imagem quebrada, pasta correta é "padroes_projetos"

2022-02-27 21:45 UTC, RcleydsonR commented on docs/padroes_projetos/estudos/padroes_emergentes.md
> +  <img src="../../../assets/padroes_projeto/mvt.png" width="800"/>
Imagem quebrada, pasta correta é "padroes_projetos"

2022-03-02 02:05 UTC, RcleydsonR approved these changes
Excelente trabalho pessoal!

2022-03-02 02:12 UTC, merged