Criação do documento de GoF's Criacionais
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #95
Opened 2022-02-27 02:48 UTC by Joao-Moura

## Descrição

Criação do documento de estudo sobre GoF's Criacionais, bem como suas metodologias e arquiteturas.

## Está consertando alguma issue aberta?

## Tarefas gerais realizadas

- Adição da introdução sobre os GoF's Criacionais
- Adição de metodologia de criação do documento
- Adição de Factory Method
- Adição de Abstract Factory
- Adição de Builder
- Adição de Prototype

2022-02-27 15:18 UTC, Denniel-sudo approved these changes
Ficou muito bom, galera! Parabéns

2022-03-02 01:45 UTC, brenno-silva requested changes
Bom trabalho galera, só algumas correções pontuais e uma sugestão abaixo

2022-03-02 01:45 UTC, brenno-silva commented on docs/padroes_projetos/estudos/gofs_criacionais.md
> +- **Produto**: Diversas implementações de **produtos abstratos**, agrupados por variantes. São criados pela **fábrica concreta** correspondente, que implementa a interface declarada no **produto abst
abstrato em `abstrado`

2022-03-02 01:45 UTC, brenno-silva commented on docs/padroes_projetos/estudos/gofs_criacionais.md
> +- **Cliente**: Faz uso das interfaces declaradas em **produto abstrato** e **fábrica abastrata**.
abstrata em `abastrata`

2022-03-02 01:45 UTC, brenno-silva commented on docs/padroes_projetos/estudos/gofs_criacionais.md
> +- **Fábrica Abstrata**: Declara uma interface ou um conjunto de métodos para a criação de qualquer **produto abstrato**.
Essa fica mais como sugestão não um erro ou problema, mas já que os diagramas estão em inglês seria interessante colocar entre parênteses o nome em inglês para facilitar a identificação nas imagens.

2022-03-02 01:45 UTC, brenno-silva commented on docs/padroes_projetos/estudos/gofs_criacionais.md
> +# Diagrama de Classes
O título está errado

2022-03-02 02:15 UTC, brenno-silva approved these changes
Tudo certo!

2022-03-02 02:17 UTC, merged