97 gofs estruturais
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs pull request #98
Opened 2022-03-04 10:58 UTC by vital14

## Descrição
Adição do documento sobre estudo dos gofs estruturais

## Está consertando alguma issue aberta?
#97 

## Tarefas gerais realizadas
- Vizualização dos vídeos para entender os padrões de projeto
- Divisão das tarefas entre os integrantes
- Criação do documento para a wiki

2022-03-04 16:30 UTC, Joao-Moura requested changes
Parabéns pelo trabalho pessoal, muito bem feito. Identifiquei umas correções pontuais e gostaria de sugerir a melhoria da qualidade das imagens.
Falo isso, porque a maioria (se não todas) foram retiradas da vídeo aula da professora e estão borradas. Recomendo usar como referência as imagens do [refactoring guru](https://refactoring.guru/pt-br/design-patterns/structural-patterns, como foi feito nos GoF's criacionais.
No mais é isso, parabéns novamente.

2022-03-04 16:30 UTC, Joao-Moura commented on docs/padroes_projetos/estudos/gofs_estruturais.md
> +<p align="justify" style="text-indent: 20px">O documento a seguir trata dos GOFS estruturais, esse tipo de padrão de projeto tem como objetivo principal diminuir o acoplamento dos objetos do sistema
Faltou um espaço em "... objetos, sendo assim,alteram ..."

2022-03-04 16:30 UTC, Joao-Moura commented on docs/padroes_projetos/estudos/gofs_estruturais.md
> +<p align="justify" style="text-indent: 20px">Esse padrão de projeto utiliza de uma classe herdeira da solução atual (Adapter) que sobrescreve os métodos do pai (Target), mantendo a mesma assinatura p
```suggestion
<p align="justify" style="text-indent: 20px">Esse padrão de projeto utiliza de uma classe herdeira da solução atual (Adapter) que sobrescreve os métodos do pai (Target), mantendo a mesma assinatura porém chamando os métodos da classe que contém a nova solução (Adapter). Com isso, o cliente (Client) continua consumindo os dados da mesma forma, porém com os resultados provenientes da nova solução [1]. Conforme exemplificado na figura 1.</p>
```
Eu mudei o Adaptee, mas é com dois 'e' mesmo ?

2022-03-04 16:30 UTC, Joao-Moura commented on docs/padroes_projetos/estudos/gofs_estruturais.md
> +<p align="justify" style="text-indent: 20px">Esse padrão de projeto parte do princípio que existe uma hierarquia na lógica de abstração e que existem elementos nessa hierarquia que se tornam muito es
```suggestion
<p align="justify" style="text-indent: 20px">Esse padrão de projeto parte do princípio que existe uma hierarquia na lógica de abstração e que existem elementos nessa hierarquia que se tornam muito específicos ou que acabam divergindo do intuito principal da abstração. Então para resolver esse problema, as duas lógicas são separadas em duas hierarquias diferentes, uma que trata sobre o foco principal e outra sobre o assunto que se divergiu [4].</p>
```
Ficaram repetidas as palavras "foco principal".

2022-03-04 16:30 UTC, Joao-Moura commented on docs/padroes_projetos/estudos/gofs_estruturais.md
> +<p align="justify" style="text-indent: 20px">O padrão de projeto proxy, tem como objetivo o controle das chamadas de um objeto através de ouro objeto que pertençam a mesma interface[7]. A classe prox
```suggestion
<p align="justify" style="text-indent: 20px">O padrão de projeto proxy, tem como objetivo o controle das chamadas de um objeto através de outros objetos que pertençam a mesma interface [7]. A classe proxy pode se conectar a qualquer objeto, sendo então, possível que se criem várias proxies para uma instância grande e complexa. Isso, facilita o controle das solicitações pois cria objetos responsáveis por esse controle.[6]</p>
```

2022-03-04 16:30 UTC, Joao-Moura commented on docs/padroes_projetos/estudos/gofs_estruturais.md
> +<p align="justify" style="text-indent: 20px">O padrão de projeto Flyweight tem como objetivo minimizar o uso de recursos quando são utilizados vários objetos no projeto. Caso existam muitos objetos i
```suggestion
<p align="justify" style="text-indent: 20px">O padrão de projeto Flyweight tem como objetivo minimizar o consumo de recursos quando são utilizados por vários objetos no programa. Caso existam muitos objetos idênticos, ele é responsável por diminuir a quantidade de memória necessária para isso.[8]</p>
```

2022-03-04 16:30 UTC, Joao-Moura commented on docs/padroes_projetos/estudos/gofs_estruturais.md
> +> [8] Design Patterns .NET: aplicando os padrões Flyweight e Decoratorl em: https://www.devmedia.com.br/design-patterns-net-aplicando-os-padroes-flyweight-e-decorator/31387. Acesso em: 03 de março de
Os links não estão clicáveis, adicionar a tag `<a href></a>` conforme já visto em outras referências.

2022-03-05 16:36 UTC, thiagohdaqw commented
:eyes:

2022-03-05 16:39 UTC, thiagohdaqw approved these changes
Bom trabalho, galera!
Não esqueçam de analisarem as sugestões do joao.

2022-03-07 15:25 UTC, vital14 commented on docs/padroes_projetos/estudos/gofs_estruturais.md
> +<p align="justify" style="text-indent: 20px">Esse padrão de projeto utiliza de uma classe herdeira da solução atual (Adapter) que sobrescreve os métodos do pai (Target), mantendo a mesma assinatura p
é isso mesmo

2022-03-07 16:55 UTC, Joao-Moura approved these changes
Show, parabéns galera

2022-03-07 16:55 UTC, merged